
-- ============================================================
-- ÁLBUM LENDAS DA BOLA 2026 — SUPABASE
-- Grupo C: Brasil, Marrocos, Haiti e Escócia
-- ============================================================

create table if not exists torcedores_copa (
  id bigint generated by default as identity primary key,
  codigo text unique not null,
  nome text not null,
  whatsapp text,
  cidade text,
  pontos integer default 0,
  total_figurinhas integer default 0,
  total_coladas integer default 0,
  total_repetidas integer default 0,
  created_at timestamp with time zone default now()
);

create table if not exists figurinhas_copa (
  id text primary key,
  numero integer not null,
  pais text not null,
  selecao text not null,
  nome text not null,
  raridade text not null,
  posicao text,
  inspiracao text,
  significado text,
  frase text,
  camisa10 boolean default false,
  imagem text,
  ativa boolean default true,
  created_at timestamp with time zone default now()
);

create table if not exists album_torcedor (
  id bigint generated by default as identity primary key,
  codigo_torcedor text not null references torcedores_copa(codigo) on delete cascade,
  figurinha_id text not null references figurinhas_copa(id) on delete cascade,
  quantidade integer default 1,
  colada boolean default false,
  origem text default 'pacote',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  unique (codigo_torcedor, figurinha_id)
);

create table if not exists missoes_copa (
  id bigint generated by default as identity primary key,
  codigo_torcedor text not null references torcedores_copa(codigo) on delete cascade,
  missao text not null,
  descricao text,
  status text default 'concluida',
  recompensa integer default 1,
  origem text,
  data_referencia date default current_date,
  total_questoes integer,
  acertos integer,
  created_at timestamp with time zone default now()
);

create table if not exists trocas_copa (
  id bigint generated by default as identity primary key,
  codigo_torcedor text not null references torcedores_copa(codigo) on delete cascade,
  tipo_troca text not null,
  custo_repetidas integer default 0,
  figurinha_recebida text references figurinhas_copa(id),
  descricao text,
  created_at timestamp with time zone default now()
);

create table if not exists palpites_copa (
  id bigint generated by default as identity primary key,
  codigo_torcedor text not null references torcedores_copa(codigo) on delete cascade,
  nome text not null,
  cidade text,
  jogo_numero integer not null,
  jogo text not null,
  palpite text not null,
  campeao text,
  pontos integer default 0,
  status text default 'pendente',
  created_at timestamp with time zone default now()
);

create table if not exists resultados_copa (
  id bigint generated by default as identity primary key,
  jogo_numero integer unique not null,
  jogo text not null,
  resultado_real text,
  vencedor text,
  status text default 'aguardando',
  updated_at timestamp with time zone default now()
);

-- Índices
create index if not exists idx_album_torcedor_codigo on album_torcedor(codigo_torcedor);
create index if not exists idx_missoes_codigo on missoes_copa(codigo_torcedor);
create index if not exists idx_palpites_codigo on palpites_copa(codigo_torcedor);
create index if not exists idx_figurinhas_pais on figurinhas_copa(pais);
create index if not exists idx_figurinhas_raridade on figurinhas_copa(raridade);

-- RLS
alter table torcedores_copa enable row level security;
alter table figurinhas_copa enable row level security;
alter table album_torcedor enable row level security;
alter table missoes_copa enable row level security;
alter table trocas_copa enable row level security;
alter table palpites_copa enable row level security;
alter table resultados_copa enable row level security;

-- Políticas públicas para site estático.
-- Observação: é simples e funcional para GitHub Pages, mas não é blindado contra fraude.
-- Depois podemos reforçar com Edge Functions ou login.

drop policy if exists "Leitura publica torcedores" on torcedores_copa;
create policy "Leitura publica torcedores"
on torcedores_copa for select
using (true);

drop policy if exists "Criar torcedor publico" on torcedores_copa;
create policy "Criar torcedor publico"
on torcedores_copa for insert
with check (true);

drop policy if exists "Atualizar torcedor publico" on torcedores_copa;
create policy "Atualizar torcedor publico"
on torcedores_copa for update
using (true)
with check (true);

drop policy if exists "Leitura publica figurinhas" on figurinhas_copa;
create policy "Leitura publica figurinhas"
on figurinhas_copa for select
using (true);

drop policy if exists "Inserir figurinhas publico" on figurinhas_copa;
create policy "Inserir figurinhas publico"
on figurinhas_copa for insert
with check (true);

drop policy if exists "Leitura publica album" on album_torcedor;
create policy "Leitura publica album"
on album_torcedor for select
using (true);

drop policy if exists "Inserir album publico" on album_torcedor;
create policy "Inserir album publico"
on album_torcedor for insert
with check (true);

drop policy if exists "Atualizar album publico" on album_torcedor;
create policy "Atualizar album publico"
on album_torcedor for update
using (true)
with check (true);

drop policy if exists "Leitura publica missoes" on missoes_copa;
create policy "Leitura publica missoes"
on missoes_copa for select
using (true);

drop policy if exists "Inserir missoes publico" on missoes_copa;
create policy "Inserir missoes publico"
on missoes_copa for insert
with check (true);

drop policy if exists "Leitura publica trocas" on trocas_copa;
create policy "Leitura publica trocas"
on trocas_copa for select
using (true);

drop policy if exists "Inserir trocas publico" on trocas_copa;
create policy "Inserir trocas publico"
on trocas_copa for insert
with check (true);

drop policy if exists "Leitura publica palpites" on palpites_copa;
create policy "Leitura publica palpites"
on palpites_copa for select
using (true);

drop policy if exists "Inserir palpites publico" on palpites_copa;
create policy "Inserir palpites publico"
on palpites_copa for insert
with check (true);

drop policy if exists "Leitura publica resultados" on resultados_copa;
create policy "Leitura publica resultados"
on resultados_copa for select
using (true);

drop policy if exists "Inserir resultados publico" on resultados_copa;
create policy "Inserir resultados publico"
on resultados_copa for insert
with check (true);

drop policy if exists "Atualizar resultados publico" on resultados_copa;
create policy "Atualizar resultados publico"
on resultados_copa for update
using (true)
with check (true);

-- ============================================================
-- Inserção das figurinhas
-- Cole também o arquivo album/figurinhas.js no site.
-- A carga no banco pode ser feita depois pelo painel/admin.
-- ============================================================

insert into figurinhas_copa (id, numero, pais, selecao, nome, raridade, posicao, inspiracao, significado, frase, camisa10, imagem)
values
('br-01', 1, 'Brasil', 'Seleção Lendária do Brasil', 'Saci Relâmpago', 'Rara', 'Atacante', 'Saci-Pererê', 'Personagem do folclore brasileiro associado à esperteza, agilidade e travessuras.', 'Some no vento e aparece na área.', false, '../img/album/brasil/br-01-saci-relampago.webp'),
('br-02', 2, 'Brasil', 'Seleção Lendária do Brasil', 'Curupira Guardião', 'Rara', 'Zagueiro', 'Curupira', 'Protetor das florestas, conhecido pelos pés virados e pela defesa da natureza.', 'Marca o caminho e protege a defesa.', false, '../img/album/brasil/br-02-curupira-guardiao.webp'),
('br-03', 3, 'Brasil', 'Seleção Lendária do Brasil', 'Iara Camisa 10', 'Cromada Dourada', 'Meia', 'Iara', 'Figura encantadora das águas no folclore brasileiro, ligada à beleza, encanto e mistério.', 'Encanta o jogo com passes de ouro.', true, '../img/album/brasil/br-03-iara-camisa-10.webp'),
('br-04', 4, 'Brasil', 'Seleção Lendária do Brasil', 'Boitatá Muralha', 'Rara', 'Zagueiro', 'Boitatá', 'Serpente de fogo do folclore brasileiro, associada à proteção das matas.', 'Defende com fogo nos olhos.', false, '../img/album/brasil/br-04-boitata-muralha.webp'),
('br-05', 5, 'Brasil', 'Seleção Lendária do Brasil', 'Boto Artilheiro', 'Incomum', 'Atacante', 'Boto-cor-de-rosa', 'Lenda amazônica ligada ao mistério, carisma e transformação.', 'Surge no ataque quando ninguém espera.', false, '../img/album/brasil/br-05-boto-artilheiro.webp'),
('br-06', 6, 'Brasil', 'Seleção Lendária do Brasil', 'Cuca Estrategista', 'Incomum', 'Técnica', 'Cuca', 'Figura popular do imaginário brasileiro, lembrada por astúcia e presença marcante.', 'Pensa o jogo antes da bola rolar.', false, '../img/album/brasil/br-06-cuca-estrategista.webp'),
('br-07', 7, 'Brasil', 'Seleção Lendária do Brasil', 'Mula Sem Cabeça Turbo', 'Incomum', 'Lateral', 'Mula sem cabeça', 'Personagem folclórica veloz e intensa, marcada por fogo e movimento.', 'Corre pela lateral como labareda.', false, '../img/album/brasil/br-07-mula-sem-cabeca-turbo.webp'),
('br-08', 8, 'Brasil', 'Seleção Lendária do Brasil', 'Vitória-Régia Encantada', 'Especial', 'Meia', 'Vitória-régia', 'Símbolo amazônico associado a beleza, água e lendas indígenas.', 'Floresce no meio-campo.', false, '../img/album/brasil/br-08-vitoria-regia-encantada.webp'),
('br-09', 9, 'Brasil', 'Seleção Lendária do Brasil', 'Guerreiro Tupã', 'Especial', 'Volante', 'Tupã', 'Referência a força, trovão e espiritualidade em tradições indígenas brasileiras.', 'O trovão que protege a seleção.', false, '../img/album/brasil/br-09-guerreiro-tupa.webp'),
('br-10', 10, 'Brasil', 'Seleção Lendária do Brasil', 'Onça da Amazônia', 'Incomum', 'Atacante', 'Onça-pintada', 'Animal símbolo de força, velocidade e domínio nas florestas brasileiras.', 'Ataca com força e silêncio.', false, '../img/album/brasil/br-10-onca-da-amazonia.webp'),
('br-11', 11, 'Brasil', 'Seleção Lendária do Brasil', 'Arara Dourada', 'Comum', 'Ponta', 'Arara', 'Ave colorida associada à natureza brasileira e à alegria tropical.', 'Voa pela ponta com brilho.', false, '../img/album/brasil/br-11-arara-dourada.webp'),
('br-12', 12, 'Brasil', 'Seleção Lendária do Brasil', 'Tambor do Maracatu', 'Comum', 'Volante', 'Maracatu', 'Expressão cultural nordestina marcada por ritmo, cortejo e tradição.', 'Dita o ritmo da partida.', false, '../img/album/brasil/br-12-tambor-do-maracatu.webp'),
('br-13', 13, 'Brasil', 'Seleção Lendária do Brasil', 'Mestre do Frevo', 'Comum', 'Meia', 'Frevo', 'Manifestação cultural pernambucana de dança rápida, cor e energia.', 'Dribla em passos impossíveis.', false, '../img/album/brasil/br-13-mestre-do-frevo.webp'),
('br-14', 14, 'Brasil', 'Seleção Lendária do Brasil', 'Capoeirista da Área', 'Incomum', 'Atacante', 'Capoeira', 'Arte afro-brasileira que une luta, dança, música e agilidade.', 'Ginga antes do chute final.', false, '../img/album/brasil/br-14-capoeirista-da-area.webp'),
('br-15', 15, 'Brasil', 'Seleção Lendária do Brasil', 'Guardião do Pantanal', 'Comum', 'Goleiro', 'Pantanal', 'Bioma brasileiro de grande biodiversidade e paisagens alagadas.', 'Fecha o gol como a imensidão do Pantanal.', false, '../img/album/brasil/br-15-guardiao-do-pantanal.webp'),
('br-16', 16, 'Brasil', 'Seleção Lendária do Brasil', 'Pescador do Rio Grande', 'Comum', 'Lateral', 'Cultura ribeirinha', 'Representa os rios, pescadores e tradições populares do Brasil.', 'Cruza como quem conhece a correnteza.', false, '../img/album/brasil/br-16-pescador-do-rio-grande.webp'),
('br-17', 17, 'Brasil', 'Seleção Lendária do Brasil', 'Estrela do Sertão', 'Comum', 'Meia', 'Sertão nordestino', 'Símbolo de resistência, criatividade e força popular.', 'Brilha mesmo no campo mais difícil.', false, '../img/album/brasil/br-17-estrela-do-sertao.webp'),
('br-18', 18, 'Brasil', 'Seleção Lendária do Brasil', 'Vaqueiro Nordestino', 'Comum', 'Zagueiro', 'Vaquejada e cultura sertaneja', 'Representa coragem, resistência e tradição do sertão.', 'Não deixa boi nem atacante passar.', false, '../img/album/brasil/br-18-vaqueiro-nordestino.webp'),
('br-19', 19, 'Brasil', 'Seleção Lendária do Brasil', 'Samba Maestro', 'Especial', 'Meia', 'Samba', 'Símbolo musical brasileiro de ritmo, criatividade e identidade popular.', 'Comanda o jogo no compasso do samba.', false, '../img/album/brasil/br-19-samba-maestro.webp'),
('br-20', 20, 'Brasil', 'Seleção Lendária do Brasil', 'Flecha Indígena', 'Incomum', 'Ponta', 'Culturas indígenas', 'Símbolo de precisão, velocidade e conexão com a terra.', 'Parte em linha reta para o gol.', false, '../img/album/brasil/br-20-flecha-indigena.webp'),
('br-21', 21, 'Brasil', 'Seleção Lendária do Brasil', 'Baiana Encantada', 'Comum', 'Meia', 'Cultura baiana', 'Representa axé, tradição, cor e força cultural.', 'Leva alegria e equilíbrio ao time.', false, '../img/album/brasil/br-21-baiana-encantada.webp'),
('br-22', 22, 'Brasil', 'Seleção Lendária do Brasil', 'Caboclo Veloz', 'Comum', 'Lateral', 'Caboclo', 'Figura cultural brasileira ligada à mistura, interior e resistência.', 'Acelera pela beira do campo.', false, '../img/album/brasil/br-22-caboclo-veloz.webp'),
('br-23', 23, 'Brasil', 'Seleção Lendária do Brasil', 'Guardião da Mata Atlântica', 'Comum', 'Zagueiro', 'Mata Atlântica', 'Bioma brasileiro associado à vida, diversidade e preservação.', 'Protege a área como floresta fechada.', false, '../img/album/brasil/br-23-guardiao-da-mata-atlantica.webp'),
('br-24', 24, 'Brasil', 'Seleção Lendária do Brasil', 'Raio Verde-Amarelo', 'Rara', 'Atacante', 'Cores do Brasil', 'Representa velocidade, energia e espírito de torcida.', 'Quando dispara, ninguém alcança.', false, '../img/album/brasil/br-24-raio-verde-amarelo.webp'),
('br-25', 25, 'Brasil', 'Seleção Lendária do Brasil', 'Torcida Canarinha', 'Comum', 'Torcida', 'Torcida brasileira', 'Símbolo da alegria popular e da paixão nacional pelo futebol.', 'Canta até a última bola.', false, '../img/album/brasil/br-25-torcida-canarinha.webp'),
('br-26', 26, 'Brasil', 'Seleção Lendária do Brasil', 'Capitão Lenda do Brasil', 'Lendária', 'Capitão', 'Herói cultural brasileiro', 'Carta máxima da Seleção Lendária do Brasil.', 'Carrega a camisa e a alma da torcida.', false, '../img/album/brasil/br-26-capitao-lenda-do-brasil.webp'),
('ma-01', 1, 'Marrocos', 'Seleção Lendária do Marrocos', 'Leão do Atlas', 'Lendária', 'Capitão', 'Leão do Atlas', 'Símbolo de força ligado ao imaginário marroquino e às montanhas do Atlas.', 'Ruge alto e lidera a seleção.', false, '../img/album/marrocos/ma-01-leao-do-atlas.webp'),
('ma-02', 2, 'Marrocos', 'Seleção Lendária do Marrocos', 'Guardião da Kasbah', 'Rara', 'Zagueiro', 'Kasbah', 'Fortificações tradicionais associadas à proteção, história e resistência.', 'Muralha viva diante do gol.', false, '../img/album/marrocos/ma-02-guardiao-da-kasbah.webp'),
('ma-03', 3, 'Marrocos', 'Seleção Lendária do Marrocos', 'Falcão do Saara', 'Rara', 'Ponta', 'Saara', 'Representa visão, velocidade e domínio dos céus do deserto.', 'Vê o passe antes de todos.', false, '../img/album/marrocos/ma-03-falcao-do-saara.webp'),
('ma-04', 4, 'Marrocos', 'Seleção Lendária do Marrocos', 'Djinn do Deserto', 'Especial', 'Meia', 'Djinn', 'Espírito sobrenatural presente em tradições do Norte da África e do mundo árabe.', 'A magia aparece no último passe.', false, '../img/album/marrocos/ma-04-djinn-do-deserto.webp'),
('ma-05', 5, 'Marrocos', 'Seleção Lendária do Marrocos', 'Cavaleiro Tbourida', 'Especial', 'Volante', 'Tbourida', 'Arte equestre tradicional marroquina, ligada a cerimônia, honra e coordenação.', 'Avança com força de cavalaria.', false, '../img/album/marrocos/ma-05-cavaleiro-tbourida.webp'),
('ma-06', 6, 'Marrocos', 'Seleção Lendária do Marrocos', 'Estrela de Marrakech', 'Cromada Dourada', 'Meia', 'Marrakech', 'Cidade símbolo de cor, energia, medinas e tradição marroquina.', 'O brilho dourado que comanda o jogo.', true, '../img/album/marrocos/ma-06-estrela-de-marrakech.webp'),
('ma-07', 7, 'Marrocos', 'Seleção Lendária do Marrocos', 'Sombra de Fez', 'Incomum', 'Meia', 'Fez', 'Cidade histórica marroquina, associada a saber, tradição e medinas antigas.', 'Joga entre as linhas como sombra.', false, '../img/album/marrocos/ma-07-sombra-de-fez.webp'),
('ma-08', 8, 'Marrocos', 'Seleção Lendária do Marrocos', 'Tambor Gnawa', 'Incomum', 'Volante', 'Música Gnawa', 'Tradição musical marroquina marcada por ritmo, espiritualidade e identidade.', 'Dá cadência ao meio-campo.', false, '../img/album/marrocos/ma-08-tambor-gnawa.webp'),
('ma-09', 9, 'Marrocos', 'Seleção Lendária do Marrocos', 'Muralha de Rabat', 'Comum', 'Zagueiro', 'Rabat', 'Capital marroquina, ligada a patrimônio, história e defesa costeira.', 'Firme como pedra antiga.', false, '../img/album/marrocos/ma-09-muralha-de-rabat.webp'),
('ma-10', 10, 'Marrocos', 'Seleção Lendária do Marrocos', 'Águia do Atlas', 'Incomum', 'Ponta', 'Montanhas do Atlas', 'Representa altitude, visão ampla e ataque veloz.', 'Sobrevoa a defesa adversária.', false, '../img/album/marrocos/ma-10-aguia-do-atlas.webp'),
('ma-11', 11, 'Marrocos', 'Seleção Lendária do Marrocos', 'Lua do Deserto', 'Comum', 'Meia', 'Paisagem do deserto', 'Símbolo de orientação, mistério e beleza noturna.', 'Ilumina o passe decisivo.', false, '../img/album/marrocos/ma-11-lua-do-deserto.webp'),
('ma-12', 12, 'Marrocos', 'Seleção Lendária do Marrocos', 'Guerreiro Amazigh', 'Especial', 'Zagueiro', 'Cultura Amazigh', 'Representa raízes culturais berberes, resistência e identidade.', 'Defende com orgulho ancestral.', false, '../img/album/marrocos/ma-12-guerreiro-amazigh.webp'),
('ma-13', 13, 'Marrocos', 'Seleção Lendária do Marrocos', 'Caravana Dourada', 'Comum', 'Meia', 'Caravanas do deserto', 'Remete a travessias, comércio e caminhos históricos.', 'Leva a bola pelo caminho certo.', false, '../img/album/marrocos/ma-13-caravana-dourada.webp'),
('ma-14', 14, 'Marrocos', 'Seleção Lendária do Marrocos', 'Guardião do Oásis', 'Comum', 'Goleiro', 'Oásis', 'Símbolo de vida, pausa e proteção no deserto.', 'Onde ele está, a bola descansa.', false, '../img/album/marrocos/ma-14-guardiao-do-oasis.webp'),
('ma-15', 15, 'Marrocos', 'Seleção Lendária do Marrocos', 'Cobra Encantada', 'Rara', 'Atacante', 'Encantadores e lendas populares', 'Figura inspirada em mistério, movimento sinuoso e cultura popular.', 'Dribla em curvas impossíveis.', false, '../img/album/marrocos/ma-15-cobra-encantada.webp'),
('ma-16', 16, 'Marrocos', 'Seleção Lendária do Marrocos', 'Estrela do Magrebe', 'Comum', 'Meia', 'Magrebe', 'Região do Norte da África marcada por diversidade cultural e histórica.', 'Brilha no centro do campo.', false, '../img/album/marrocos/ma-16-estrela-do-magrebe.webp'),
('ma-17', 17, 'Marrocos', 'Seleção Lendária do Marrocos', 'Marujo de Casablanca', 'Comum', 'Lateral', 'Casablanca', 'Cidade costeira e moderna de Marrocos, ligada ao Atlântico.', 'Cruza ondas pela lateral.', false, '../img/album/marrocos/ma-17-marujo-de-casablanca.webp'),
('ma-18', 18, 'Marrocos', 'Seleção Lendária do Marrocos', 'Areia Relâmpago', 'Incomum', 'Atacante', 'Dunas do deserto', 'Símbolo de velocidade e imprevisibilidade.', 'Escapa como areia no vento.', false, '../img/album/marrocos/ma-18-areia-relampago.webp'),
('ma-19', 19, 'Marrocos', 'Seleção Lendária do Marrocos', 'Tapete Voador do Gol', 'Rara', 'Meia', 'Imaginação oriental', 'Imagem fantástica ligada a voo, fantasia e deslocamento mágico.', 'Levanta a bola com encanto.', false, '../img/album/marrocos/ma-19-tapete-voador-do-gol.webp'),
('ma-20', 20, 'Marrocos', 'Seleção Lendária do Marrocos', 'Escudo de Chefchaouen', 'Comum', 'Zagueiro', 'Chefchaouen', 'Cidade azul marroquina, famosa por beleza visual e identidade marcante.', 'Azul, firme e elegante.', false, '../img/album/marrocos/ma-20-escudo-de-chefchaouen.webp'),
('ma-21', 21, 'Marrocos', 'Seleção Lendária do Marrocos', 'Azul da Medina', 'Comum', 'Meia', 'Medinas marroquinas', 'Representa vielas, cores e tradição urbana.', 'Encontra espaços onde ninguém vê.', false, '../img/album/marrocos/ma-21-azul-da-medina.webp'),
('ma-22', 22, 'Marrocos', 'Seleção Lendária do Marrocos', 'Porta do Deserto', 'Comum', 'Zagueiro', 'Saara marroquino', 'Símbolo de entrada, resistência e travessia.', 'Fecha a passagem do ataque.', false, '../img/album/marrocos/ma-22-porta-do-deserto.webp'),
('ma-23', 23, 'Marrocos', 'Seleção Lendária do Marrocos', 'Montanha Toubkal', 'Comum', 'Goleiro', 'Monte Toubkal', 'Ponto mais alto do Atlas, símbolo de grandeza e resistência.', 'Alto demais para ser vencido.', false, '../img/album/marrocos/ma-23-montanha-toubkal.webp'),
('ma-24', 24, 'Marrocos', 'Seleção Lendária do Marrocos', 'Dança das Dunas', 'Comum', 'Ponta', 'Dunas', 'Movimento das areias e beleza do deserto.', 'Dança antes do cruzamento.', false, '../img/album/marrocos/ma-24-danca-das-dunas.webp'),
('ma-25', 25, 'Marrocos', 'Seleção Lendária do Marrocos', 'Fogo de Marrakech', 'Incomum', 'Atacante', 'Energia cultural de Marrakech', 'Representa intensidade, cor e paixão popular.', 'Acende o ataque em segundos.', false, '../img/album/marrocos/ma-25-fogo-de-marrakech.webp'),
('ma-26', 26, 'Marrocos', 'Seleção Lendária do Marrocos', 'Capitão Rubro-Verde', 'Incomum', 'Capitão', 'Cores nacionais', 'Personagem original inspirado nas cores e na força da torcida marroquina.', 'Comanda com coração vermelho e verde.', false, '../img/album/marrocos/ma-26-capitao-rubro-verde.webp'),
('ht-01', 1, 'Haiti', 'Seleção Lendária do Haiti', 'Bawon Samdi Guardião', 'Lendária', 'Capitão', 'Bawon Samdi', 'Figura do Vodou haitiano associada aos Gede e à passagem entre mundos.', 'Protege a meta entre dois mundos.', false, '../img/album/haiti/ht-01-bawon-samdi-guardiao.webp'),
('ht-02', 2, 'Haiti', 'Seleção Lendária do Haiti', 'Damballa Serpente', 'Especial', 'Zagueiro', 'Damballa', 'Espírito-serpente ligado à criação, sabedoria e continuidade em tradições vodou.', 'Desliza e fecha todos os espaços.', false, '../img/album/haiti/ht-02-damballa-serpente.webp'),
('ht-03', 3, 'Haiti', 'Seleção Lendária do Haiti', 'Ezili Camisa 10', 'Cromada Dourada', 'Meia', 'Ezili', 'Figura associada ao amor, emoção, beleza e força espiritual no Vodou haitiano.', 'Joga com emoção e passe dourado.', true, '../img/album/haiti/ht-03-ezili-camisa-10.webp'),
('ht-04', 4, 'Haiti', 'Seleção Lendária do Haiti', 'Ogou Guerreiro', 'Rara', 'Volante', 'Ogou', 'Espírito guerreiro ligado à força, coragem e luta.', 'Vence divididas como batalha.', false, '../img/album/haiti/ht-04-ogou-guerreiro.webp'),
('ht-05', 5, 'Haiti', 'Seleção Lendária do Haiti', 'Gede da Área', 'Rara', 'Atacante', 'Gede', 'Família de espíritos ligada aos mortos, irreverência e transformação.', 'Aparece na área com ousadia.', false, '../img/album/haiti/ht-05-gede-da-area.webp'),
('ht-06', 6, 'Haiti', 'Seleção Lendária do Haiti', 'Tambor de Porto Príncipe', 'Incomum', 'Volante', 'Tambor haitiano', 'Representa ritmo, celebração e identidade musical do Haiti.', 'Marca o tempo da partida.', false, '../img/album/haiti/ht-06-tambor-de-porto-principe.webp'),
('ht-07', 7, 'Haiti', 'Seleção Lendária do Haiti', 'Raiz Taína', 'Incomum', 'Meia', 'Herança Taína', 'Referência às raízes indígenas caribenhas presentes na história haitiana.', 'Joga ligado à raiz da ilha.', false, '../img/album/haiti/ht-07-raiz-taina.webp'),
('ht-08', 8, 'Haiti', 'Seleção Lendária do Haiti', 'Espírito do Caribe', 'Incomum', 'Ponta', 'Caribe', 'Símbolo de mar, calor, movimento e mistura cultural.', 'Corre com vento de ilha.', false, '../img/album/haiti/ht-08-espirito-do-caribe.webp'),
('ht-09', 9, 'Haiti', 'Seleção Lendária do Haiti', 'Sol de Jacmel', 'Comum', 'Atacante', 'Jacmel', 'Cidade conhecida por arte, cultura e carnaval.', 'Brilha quando o jogo esquenta.', false, '../img/album/haiti/ht-09-sol-de-jacmel.webp'),
('ht-10', 10, 'Haiti', 'Seleção Lendária do Haiti', 'Guardião da Liberdade', 'Especial', 'Zagueiro', 'História haitiana', 'Referência à luta por liberdade e independência do Haiti.', 'Defende como quem protege uma conquista.', false, '../img/album/haiti/ht-10-guardiao-da-liberdade.webp'),
('ht-11', 11, 'Haiti', 'Seleção Lendária do Haiti', 'Montanha Azul', 'Comum', 'Goleiro', 'Paisagem haitiana', 'Símbolo de altura, firmeza e natureza do país.', 'Grande como montanha no gol.', false, '../img/album/haiti/ht-11-montanha-azul.webp'),
('ht-12', 12, 'Haiti', 'Seleção Lendária do Haiti', 'Maré Haitiana', 'Comum', 'Lateral', 'Mar do Caribe', 'Representa fluxo, força e movimento constante.', 'Sobe e desce como maré.', false, '../img/album/haiti/ht-12-mare-haitiana.webp'),
('ht-13', 13, 'Haiti', 'Seleção Lendária do Haiti', 'Carnaval de Jacmel', 'Rara', 'Meia', 'Carnaval de Jacmel', 'Expressão cultural famosa por máscaras, cores e criatividade.', 'Transforma o jogo em festa.', false, '../img/album/haiti/ht-13-carnaval-de-jacmel.webp'),
('ht-14', 14, 'Haiti', 'Seleção Lendária do Haiti', 'Pássaro Tropical', 'Comum', 'Ponta', 'Fauna caribenha', 'Representa leveza, voo e cor.', 'Abre as asas pela ponta.', false, '../img/album/haiti/ht-14-passaro-tropical.webp'),
('ht-15', 15, 'Haiti', 'Seleção Lendária do Haiti', 'Pérola do Caribe', 'Comum', 'Meia', 'Haiti caribenho', 'Imagem de beleza, valor cultural e identidade insular.', 'Brilha mesmo sob pressão.', false, '../img/album/haiti/ht-15-perola-do-caribe.webp'),
('ht-16', 16, 'Haiti', 'Seleção Lendária do Haiti', 'Pintor das Cores', 'Incomum', 'Meia', 'Arte haitiana', 'Referência à pintura popular haitiana, marcada por cores vivas.', 'Pinta jogadas no gramado.', false, '../img/album/haiti/ht-16-pintor-das-cores.webp'),
('ht-17', 17, 'Haiti', 'Seleção Lendária do Haiti', 'Fortaleza da Independência', 'Incomum', 'Zagueiro', 'Independência haitiana', 'Símbolo de resistência histórica e orgulho nacional.', 'Firme como uma fortaleza.', false, '../img/album/haiti/ht-17-fortaleza-da-independencia.webp'),
('ht-18', 18, 'Haiti', 'Seleção Lendária do Haiti', 'Vento de Cap-Haïtien', 'Comum', 'Lateral', 'Cap-Haïtien', 'Cidade histórica do norte do Haiti.', 'Chega rápido pelo corredor.', false, '../img/album/haiti/ht-18-vento-de-cap-haitien.webp'),
('ht-19', 19, 'Haiti', 'Seleção Lendária do Haiti', 'Ritmo Rara', 'Rara', 'Volante', 'Rara haitiana', 'Tradição musical de rua com tambores, metais e energia coletiva.', 'Rouba a bola no compasso.', false, '../img/album/haiti/ht-19-ritmo-rara.webp'),
('ht-20', 20, 'Haiti', 'Seleção Lendária do Haiti', 'Chama da Resistência', 'Incomum', 'Atacante', 'Resistência haitiana', 'Representa força, superação e coragem popular.', 'Nunca se apaga no ataque.', false, '../img/album/haiti/ht-20-chama-da-resistencia.webp'),
('ht-21', 21, 'Haiti', 'Seleção Lendária do Haiti', 'Guardião do Tambor', 'Comum', 'Goleiro', 'Música haitiana', 'Símbolo de ritmo, proteção e tradição.', 'Defende no ritmo certo.', false, '../img/album/haiti/ht-21-guardiao-do-tambor.webp'),
('ht-22', 22, 'Haiti', 'Seleção Lendária do Haiti', 'Dança do Sol', 'Comum', 'Meia', 'Cultura popular caribenha', 'Representa alegria, calor e movimento.', 'Gira o jogo para o lado certo.', false, '../img/album/haiti/ht-22-danca-do-sol.webp'),
('ht-23', 23, 'Haiti', 'Seleção Lendária do Haiti', 'Noite Estrelada do Haiti', 'Comum', 'Meia', 'Céu caribenho', 'Símbolo poético de esperança e beleza.', 'Encontra luz em jogo fechado.', false, '../img/album/haiti/ht-23-noite-estrelada-do-haiti.webp'),
('ht-24', 24, 'Haiti', 'Seleção Lendária do Haiti', 'Mar Azul Profundo', 'Comum', 'Zagueiro', 'Mar do Caribe', 'Representa profundidade, calma e força natural.', 'Fecha a área com calma azul.', false, '../img/album/haiti/ht-24-mar-azul-profundo.webp'),
('ht-25', 25, 'Haiti', 'Seleção Lendária do Haiti', 'Flecha Caribenha', 'Comum', 'Atacante', 'Energia caribenha', 'Símbolo de velocidade, direção e ataque.', 'Dispara direto para o gol.', false, '../img/album/haiti/ht-25-flecha-caribenha.webp'),
('ht-26', 26, 'Haiti', 'Seleção Lendária do Haiti', 'Capitão Grenadiers', 'Especial', 'Capitão', 'Apelido da seleção haitiana', 'Personagem original inspirado no orgulho esportivo haitiano.', 'Lidera com coragem grenadier.', false, '../img/album/haiti/ht-26-capitao-grenadiers.webp'),
('sc-01', 1, 'Escócia', 'Seleção Lendária da Escócia', 'Unicórnio Capitão', 'Lendária', 'Capitão', 'Unicórnio escocês', 'Símbolo nacional da Escócia, associado à força, pureza e independência.', 'Lidera com força mítica.', false, '../img/album/escocia/sc-01-unicornio-capitao.webp'),
('sc-02', 2, 'Escócia', 'Seleção Lendária da Escócia', 'Kelpie Veloz', 'Especial', 'Atacante', 'Kelpie', 'Espírito aquático do folclore escocês que assume forma de cavalo.', 'Corre como criatura das águas.', false, '../img/album/escocia/sc-02-kelpie-veloz.webp'),
('sc-03', 3, 'Escócia', 'Seleção Lendária da Escócia', 'Nessie Muralha', 'Especial', 'Goleiro', 'Monstro do Lago Ness', 'Criatura lendária associada ao Lago Ness e ao mistério escocês.', 'No lago ou na área, ninguém passa.', false, '../img/album/escocia/sc-03-nessie-muralha.webp'),
('sc-04', 4, 'Escócia', 'Seleção Lendária da Escócia', 'Selkie Camisa 10', 'Cromada Dourada', 'Meia', 'Selkie', 'Criatura que alterna entre foca e forma humana no folclore escocês.', 'Transforma defesa em ataque com passe dourado.', true, '../img/album/escocia/sc-04-selkie-camisa-10.webp'),
('sc-05', 5, 'Escócia', 'Seleção Lendária da Escócia', 'Wulver Protetor', 'Rara', 'Zagueiro', 'Wulver', 'Figura benevolente parecida com homem-lobo no folclore das Shetland.', 'Feroz, leal e protetor.', false, '../img/album/escocia/sc-05-wulver-protetor.webp'),
('sc-06', 6, 'Escócia', 'Seleção Lendária da Escócia', 'Guerreiro das Highlands', 'Especial', 'Volante', 'Highlands', 'Terras Altas escocesas, ligadas a clãs, força e paisagens marcantes.', 'Vence no coração das montanhas.', false, '../img/album/escocia/sc-06-guerreiro-das-highlands.webp'),
('sc-07', 7, 'Escócia', 'Seleção Lendária da Escócia', 'Gaita de Guerra', 'Incomum', 'Meia', 'Gaita de foles', 'Instrumento tradicional associado à cultura e cerimônias escocesas.', 'O som que empurra o time.', false, '../img/album/escocia/sc-07-gaita-de-guerra.webp'),
('sc-08', 8, 'Escócia', 'Seleção Lendária da Escócia', 'Guardião do Castelo', 'Incomum', 'Zagueiro', 'Castelos escoceses', 'Representa muralhas, história e defesa.', 'Defende como torre de pedra.', false, '../img/album/escocia/sc-08-guardiao-do-castelo.webp'),
('sc-09', 9, 'Escócia', 'Seleção Lendária da Escócia', 'Falcão das Terras Altas', 'Comum', 'Ponta', 'Highlands', 'Símbolo de visão e velocidade nos céus das montanhas.', 'Voa acima da marcação.', false, '../img/album/escocia/sc-09-falcao-das-terras-altas.webp'),
('sc-10', 10, 'Escócia', 'Seleção Lendária da Escócia', 'Escudo de Tartan', 'Comum', 'Zagueiro', 'Tartan', 'Padrão têxtil ligado a clãs e identidade escocesa.', 'Marca com orgulho de clã.', false, '../img/album/escocia/sc-10-escudo-de-tartan.webp'),
('sc-11', 11, 'Escócia', 'Seleção Lendária da Escócia', 'Martelo Celta', 'Rara', 'Volante', 'Cultura celta', 'Imagem de força, tradição e impacto.', 'Chega firme na dividida.', false, '../img/album/escocia/sc-11-martelo-celta.webp'),
('sc-12', 12, 'Escócia', 'Seleção Lendária da Escócia', 'Nevoeiro do Lago', 'Comum', 'Meia', 'Lagos escoceses', 'Representa mistério, calma e surpresa.', 'Some no nevoeiro e acha o passe.', false, '../img/album/escocia/sc-12-nevoeiro-do-lago.webp'),
('sc-13', 13, 'Escócia', 'Seleção Lendária da Escócia', 'Corvo das Highlands', 'Incomum', 'Meia', 'Fauna e lendas das Highlands', 'Símbolo de inteligência, presságio e visão.', 'Lê o jogo antes da jogada.', false, '../img/album/escocia/sc-13-corvo-das-highlands.webp'),
('sc-14', 14, 'Escócia', 'Seleção Lendária da Escócia', 'Pedra de Scone', 'Incomum', 'Zagueiro', 'Pedra de Scone', 'Símbolo histórico associado à coroação e identidade escocesa.', 'Firme como tradição antiga.', false, '../img/album/escocia/sc-14-pedra-de-scone.webp'),
('sc-15', 15, 'Escócia', 'Seleção Lendária da Escócia', 'Cervo Real', 'Comum', 'Atacante', 'Cervo das Highlands', 'Animal associado à nobreza, velocidade e paisagem escocesa.', 'Salta para o gol.', false, '../img/album/escocia/sc-15-cervo-real.webp'),
('sc-16', 16, 'Escócia', 'Seleção Lendária da Escócia', 'Espírito do Clã', 'Rara', 'Capitão', 'Clãs escoceses', 'Representa união, honra e identidade familiar.', 'Joga por todos do clã.', false, '../img/album/escocia/sc-16-espirito-do-cla.webp'),
('sc-17', 17, 'Escócia', 'Seleção Lendária da Escócia', 'Barco das Ilhas', 'Comum', 'Lateral', 'Ilhas escocesas', 'Referência às travessias e paisagens marítimas.', 'Navega pela lateral.', false, '../img/album/escocia/sc-17-barco-das-ilhas.webp'),
('sc-18', 18, 'Escócia', 'Seleção Lendária da Escócia', 'Chuva do Norte', 'Comum', 'Volante', 'Clima escocês', 'Representa resistência e adaptação às condições difíceis.', 'Não para nem na tempestade.', false, '../img/album/escocia/sc-18-chuva-do-norte.webp'),
('sc-19', 19, 'Escócia', 'Seleção Lendária da Escócia', 'Flauta Celta', 'Comum', 'Meia', 'Música celta', 'Símbolo de melodia, tradição e leveza.', 'Faz a bola cantar.', false, '../img/album/escocia/sc-19-flauta-celta.webp'),
('sc-20', 20, 'Escócia', 'Seleção Lendária da Escócia', 'Lenda do Lago Ness', 'Incomum', 'Zagueiro', 'Lago Ness', 'Referência ao mistério e às narrativas do lago.', 'Aparece quando o perigo chega.', false, '../img/album/escocia/sc-20-lenda-do-lago-ness.webp'),
('sc-21', 21, 'Escócia', 'Seleção Lendária da Escócia', 'Guardião de Edimburgo', 'Comum', 'Goleiro', 'Edimburgo', 'Capital escocesa, ligada a castelos e patrimônio histórico.', 'Fecha o gol como fortaleza.', false, '../img/album/escocia/sc-21-guardiao-de-edimburgo.webp'),
('sc-22', 22, 'Escócia', 'Seleção Lendária da Escócia', 'Fogo de Beltane', 'Incomum', 'Atacante', 'Festival de Beltane', 'Referência a tradições celtas de fogo, primavera e celebração.', 'Acende a partida no ataque.', false, '../img/album/escocia/sc-22-fogo-de-beltane.webp'),
('sc-23', 23, 'Escócia', 'Seleção Lendária da Escócia', 'Cavaleiro Azul', 'Comum', 'Zagueiro', 'Cores escocesas', 'Personagem original inspirado na força azul da seleção lendária.', 'Defende com honra azul.', false, '../img/album/escocia/sc-23-cavaleiro-azul.webp'),
('sc-24', 24, 'Escócia', 'Seleção Lendária da Escócia', 'Montanha Ben Nevis', 'Comum', 'Goleiro', 'Ben Nevis', 'Montanha mais alta do Reino Unido, símbolo de grandeza e desafio.', 'Alto como o Ben Nevis.', false, '../img/album/escocia/sc-24-montanha-ben-nevis.webp'),
('sc-25', 25, 'Escócia', 'Seleção Lendária da Escócia', 'Torcida Tartan', 'Comum', 'Torcida', 'Torcida escocesa', 'Representa festa, cantos, bandeiras e identidade popular.', 'Canta até o apito final.', false, '../img/album/escocia/sc-25-torcida-tartan.webp'),
('sc-26', 26, 'Escócia', 'Seleção Lendária da Escócia', 'Capitão Coração das Highlands', 'Rara', 'Capitão', 'Highlands', 'Personagem original inspirado na coragem e no espírito das Terras Altas.', 'Coração forte, jogo gigante.', false, '../img/album/escocia/sc-26-capitao-coracao-das-highlands.webp')
on conflict (id) do update set
  nome = excluded.nome,
  raridade = excluded.raridade,
  posicao = excluded.posicao,
  inspiracao = excluded.inspiracao,
  significado = excluded.significado,
  frase = excluded.frase,
  camisa10 = excluded.camisa10,
  imagem = excluded.imagem;
