window.FICHAS_TECNICAS = window.FICHAS_TECNICAS || {};
// Fichas técnicas - GRUPO-E
Object.assign(window.FICHAS_TECNICAS, {
  "grupo-e-alemanha-01": {
    "nome": "Otto von Bismarck",
    "pais": "Alemanha",
    "grupo": "Grupo E",
    "numero": 1,
    "posicao": "Goleiro",
    "raridade": "Lendário",
    "periodo": "1815-1898",
    "resumo": "Estadista conservador prussiano que unificou a Alemanha em 1871.",
    "legado": "Primeiro chanceler do Império Alemão, estabeleceu o primeiro estado de bem-estar social moderno e o complexo sistema de alianças na Europa."
  },
  "grupo-e-alemanha-02": {
    "nome": "Albert Einstein",
    "pais": "Alemanha",
    "grupo": "Grupo E",
    "numero": 2,
    "posicao": "Lateral",
    "raridade": "Comum",
    "periodo": "1879-1955",
    "resumo": "Físico teórico, amplamente reconhecido como um dos maiores cientistas de todos os tempos.",
    "legado": "Desenvolveu a teoria da relatividade, mudando fundamentalmente a compreensão humana sobre espaço, tempo e gravidade."
  },
  "grupo-e-alemanha-03": {
    "nome": "Johann Sebastian Bach",
    "pais": "Alemanha",
    "grupo": "Grupo E",
    "numero": 3,
    "posicao": "Zagueiro",
    "raridade": "Raro",
    "periodo": "1685-1750",
    "resumo": "Compositor e músico do período Barroco.",
    "legado": "Sua genialidade em contraponto, harmonia e desenvolvimento motívico formou a base imortal da música clássica ocidental."
  },
  "grupo-e-alemanha-04": {
    "nome": "Immanuel Kant",
    "pais": "Alemanha",
    "grupo": "Grupo E",
    "numero": 4,
    "posicao": "Zagueiro",
    "raridade": "Comum",
    "periodo": "1724-1804",
    "resumo": "Filósofo central da era do Iluminismo.",
    "legado": "Suas obras, especialmente a \"Crítica da Razão Pura\", revolucionaram a epistemologia, a ética e a estética no pensamento ocidental."
  },
  "grupo-e-alemanha-05": {
    "nome": "Rosa Luxemburg",
    "pais": "Alemanha",
    "grupo": "Grupo E",
    "numero": 5,
    "posicao": "Lateral",
    "raridade": "Lendário",
    "periodo": "1871-1919",
    "resumo": "Teórica marxista, filósofa e líder revolucionária anti-guerra.",
    "legado": "Fundou a Liga Espartaquista e o Partido Comunista da Alemanha, deixando um forte legado no pensamento socialista democrático."
  },
  "grupo-e-alemanha-06": {
    "nome": "Johann Wolfgang von Goethe",
    "pais": "Alemanha",
    "grupo": "Grupo E",
    "numero": 6,
    "posicao": "Volante",
    "raridade": "Comum",
    "periodo": "1749-1832",
    "resumo": "Escritor, cientista, estadista e figura central do movimento literário Sturm und Drang e do Classicismo de Weimar.",
    "legado": "Autor de \"Fausto\", é considerado o maior gênio literário da língua alemã."
  },
  "grupo-e-alemanha-07": {
    "nome": "Ludwig van Beethoven",
    "pais": "Alemanha",
    "grupo": "Grupo E",
    "numero": 7,
    "posicao": "Meia",
    "raridade": "Épico",
    "periodo": "1770-1827",
    "resumo": "Compositor e pianista que marcou a transição entre as eras Clássica e Romântica da música ocidental.",
    "legado": "Continuou a compor obras-primas, como a Nona Sinfonia, mesmo após perder completamente a audição, simbolizando o triunfo do espírito humano."
  },
  "grupo-e-alemanha-08": {
    "nome": "Karl Marx",
    "pais": "Alemanha",
    "grupo": "Grupo E",
    "numero": 8,
    "posicao": "Meia",
    "raridade": "Comum",
    "periodo": "1818-1883",
    "resumo": "Filósofo, economista, historiador e teórico político.",
    "legado": "Co-autor do \"Manifesto Comunista\" e autor de \"O Capital\", suas ideias sobre luta de classes formaram a base do marxismo e moldaram a geopolítica mundial."
  },
  "grupo-e-alemanha-09": {
    "nome": "Marlene Dietrich",
    "pais": "Alemanha",
    "grupo": "Grupo E",
    "numero": 9,
    "posicao": "Ponta",
    "raridade": "Raro",
    "periodo": "1901-1992",
    "resumo": "Atriz e cantora com uma carreira duradoura em Hollywood e na Europa.",
    "legado": "Ícone de estilo e do cinema clássico, notabilizou-se também pelo seu fervoroso ativismo antinazista durante a Segunda Guerra Mundial."
  },
  "grupo-e-alemanha-10": {
    "nome": "Friedrich Nietzsche",
    "pais": "Alemanha",
    "grupo": "Grupo E",
    "numero": 10,
    "posicao": "Camisa 10",
    "raridade": "Comum",
    "periodo": "1844-1900",
    "resumo": "Filósofo, crítico cultural, compositor e filólogo.",
    "legado": "Conceitos como a \"Morte de Deus\", o \"Übermensch\" (Super-homem) e a \"Vontade de Poder\" influenciaram profundamente a filosofia existencial e a literatura do século XX."
  },
  "grupo-e-alemanha-11": {
    "nome": "Johannes Gutenberg",
    "pais": "Alemanha",
    "grupo": "Grupo E",
    "numero": 11,
    "posicao": "Centroavante",
    "raridade": "Comum",
    "periodo": "1400-1468",
    "resumo": "Ourives e inventor do século XV.",
    "legado": "Introduziu a impressão com tipos móveis mecânicos na Europa, iniciando a Revolução da Imprensa e democratizando o conhecimento."
  },
  "grupo-e-alemanha-12": {
    "nome": "Sophie Scholl",
    "pais": "Alemanha",
    "grupo": "Grupo E",
    "numero": 12,
    "posicao": "Técnica",
    "raridade": "Lendário",
    "periodo": "1921-1943",
    "resumo": "Estudante e ativista fundamental do grupo de resistência pacífica \"Rosa Branca\" (Weiße Rose).",
    "legado": "Executada por distribuir panfletos anti-guerra e anti-nazistas, tornou-se um símbolo imortal de coragem civil e oposição à tirania."
  },
  "grupo-e-costa-do-marfim-01": {
    "nome": "Félix Houphouët-Boigny",
    "pais": "Costa do Marfim",
    "grupo": "Grupo E",
    "numero": 1,
    "posicao": "Goleiro",
    "raridade": "Lendário",
    "periodo": "1905-1993",
    "resumo": "Líder da independência e o primeiro presidente da Costa do Marfim, governando por mais de três décadas.",
    "legado": "Conduziu a nação a um período prolongado de prosperidade econômica e estabilidade política, conhecido como o \"Milagre Ivoiriano\"."
  },
  "grupo-e-costa-do-marfim-02": {
    "nome": "Rainha Abla Pokou",
    "pais": "Costa do Marfim",
    "grupo": "Grupo E",
    "numero": 2,
    "posicao": "Lateral",
    "raridade": "Comum",
    "periodo": "Século XVIII",
    "resumo": "Princesa e líder do povo Baoulé durante a sua grande migração no século XVIII.",
    "legado": "Figura mítica fundadora; a lenda de seu sacrifício no rio Comoé para salvar seu povo é pilar fundamental da identidade Baoulé."
  },
  "grupo-e-costa-do-marfim-03": {
    "nome": "Victor Biaka Boda",
    "pais": "Costa do Marfim",
    "grupo": "Grupo E",
    "numero": 3,
    "posicao": "Zagueiro",
    "raridade": "Raro",
    "periodo": "1913-1950",
    "resumo": "Médico, político e figura influente no Partido Democrático da Costa do Marfim (PDCI).",
    "legado": "Atuou como senador em Paris e é lembrado como um mártir do movimento anticolonial após seu trágico assassinato."
  },
  "grupo-e-costa-do-marfim-04": {
    "nome": "Bernard Dadié",
    "pais": "Costa do Marfim",
    "grupo": "Grupo E",
    "numero": 4,
    "posicao": "Zagueiro",
    "raridade": "Comum",
    "periodo": "1916-2019",
    "resumo": "Prolífico romancista, poeta, dramaturgo e ativista da descolonização.",
    "legado": "Considerado o \"pai da literatura marfinense\", sua obra promoveu o folclore africano e criticou severamente o colonialismo."
  },
  "grupo-e-costa-do-marfim-05": {
    "nome": "Marie Koré",
    "pais": "Costa do Marfim",
    "grupo": "Grupo E",
    "numero": 5,
    "posicao": "Lateral",
    "raridade": "Lendário",
    "periodo": "1910-1953",
    "resumo": "Ativista fervorosa da emancipação e figura de destaque nas marchas anti-coloniais.",
    "legado": "Liderou a famosa e corajosa Marcha das Mulheres em Grand-Bassam em 1949, exigindo a libertação dos líderes políticos presos."
  },
  "grupo-e-costa-do-marfim-06": {
    "nome": "Ahmadou Kourouma",
    "pais": "Costa do Marfim",
    "grupo": "Grupo E",
    "numero": 6,
    "posicao": "Volante",
    "raridade": "Comum",
    "periodo": "1927-2003",
    "resumo": "Um dos maiores romancistas africanos de expressão francesa.",
    "legado": "Revolucionou a literatura pós-colonial com seu estilo inovador e crítica afiada a regimes ditatoriais africanos em obras como \"Os Sóis das Independências\"."
  },
  "grupo-e-costa-do-marfim-07": {
    "nome": "Laurent Pokou",
    "pais": "Costa do Marfim",
    "grupo": "Grupo E",
    "numero": 7,
    "posicao": "Meia",
    "raridade": "Épico",
    "periodo": "1947-2016",
    "resumo": "Atleta lendário e o maior futebolista da história inicial do país.",
    "legado": "Marcou época como o \"Homem de Asmara\"; deteve o recorde de maior artilheiro da história da Copa das Nações Africanas durante décadas."
  },
  "grupo-e-costa-do-marfim-08": {
    "nome": "Auguste Denise",
    "pais": "Costa do Marfim",
    "grupo": "Grupo E",
    "numero": 8,
    "posicao": "Meia",
    "raridade": "Comum",
    "periodo": "1906-1991",
    "resumo": "Médico, estadista e uma das figuras fundadoras do movimento político moderno do país.",
    "legado": "Foi o Chefe de Governo da Costa do Marfim pouco antes da independência completa, um pilar da transição pacífica e da estabilidade."
  },
  "grupo-e-costa-do-marfim-09": {
    "nome": "Mathieu Ekra",
    "pais": "Costa do Marfim",
    "grupo": "Grupo E",
    "numero": 9,
    "posicao": "Ponta",
    "raridade": "Raro",
    "periodo": "1917-2015",
    "resumo": "Estadista de alto escalão e aliado-chave durante a construção da nação pós-independência.",
    "legado": "Co-autor do hino nacional do país, \"L'Abidjanaise\", e ministro que conduziu importantes negociações diplomáticas."
  },
  "grupo-e-costa-do-marfim-10": {
    "nome": "Jean-Baptiste Mockey",
    "pais": "Costa do Marfim",
    "grupo": "Grupo E",
    "numero": 10,
    "posicao": "Camisa 10",
    "raridade": "Comum",
    "periodo": "1915-1981",
    "resumo": "Farmacêutico, estadista e líder proeminente no partido nacional pela independência.",
    "legado": "Figura altamente influente na formação governamental do início da república, enfrentando também prisões devido a disputas políticas."
  },
  "grupo-e-costa-do-marfim-11": {
    "nome": "Georges Ouégnin",
    "pais": "Costa do Marfim",
    "grupo": "Grupo E",
    "numero": 11,
    "posicao": "Centroavante",
    "raridade": "Comum",
    "periodo": "1934-presente",
    "resumo": "Chefe do Protocolo de Estado da Presidência durante quarenta anos consecutivos.",
    "legado": "Lenda da diplomacia nos bastidores, garantiu o prestígio e a organização impecável do estado marfinense por décadas sob diferentes presidentes."
  },
  "grupo-e-costa-do-marfim-12": {
    "nome": "Anne-Marie Raggi",
    "pais": "Costa do Marfim",
    "grupo": "Grupo E",
    "numero": 12,
    "posicao": "Técnica",
    "raridade": "Lendário",
    "periodo": "1918-2004",
    "resumo": "Militante incansável pelos direitos das mulheres e ativista da independência.",
    "legado": "Exerceu um papel organizativo indispensável na \"Marcha das Mulheres de Bassam\" e foi a primeira mulher vereadora em Abidjan."
  },
  "grupo-e-curacao-01": {
    "nome": "Ergilio Hato",
    "pais": "Curaçao",
    "grupo": "Grupo E",
    "numero": 1,
    "posicao": "Goleiro",
    "raridade": "Lendário",
    "periodo": "1926-2003",
    "resumo": "Conhecido como a \"Pantera Negra\", foi o jogador de futebol mais famoso das Antilhas Holandesas.",
    "legado": "Recusou ofertas milionárias de clubes europeus e sul-americanos para permanecer amador e fiel ao seu país; o estádio nacional leva seu nome."
  },
  "grupo-e-curacao-02": {
    "nome": "Pedro Luis Brion",
    "pais": "Curaçao",
    "grupo": "Grupo E",
    "numero": 2,
    "posicao": "Lateral",
    "raridade": "Comum",
    "periodo": "1782-1821",
    "resumo": "Oficial militar naval, almirante das frotas da Grande Colômbia.",
    "legado": "Combateu lado a lado com Simón Bolívar nas Guerras de Independência da América do Sul contra o Império Espanhol."
  },
  "grupo-e-curacao-03": {
    "nome": "Manuel Piar",
    "pais": "Curaçao",
    "grupo": "Grupo E",
    "numero": 3,
    "posicao": "Zagueiro",
    "raridade": "Raro",
    "periodo": "1774-1817",
    "resumo": "General-Chefe dos exércitos patriotas durante a guerra de independência da Venezuela.",
    "legado": "Liderou importantes vitórias militares, notavelmente a conquista de Guayana, fundamental para a causa republicana de Bolívar."
  },
  "grupo-e-curacao-04": {
    "nome": "George Maduro",
    "pais": "Curaçao",
    "grupo": "Grupo E",
    "numero": 4,
    "posicao": "Zagueiro",
    "raridade": "Comum",
    "periodo": "1916-1945",
    "resumo": "Estudante de direito e herói militar durante a Segunda Guerra Mundial na Batalha dos Países Baixos.",
    "legado": "Condecorado postumamente com a maior honraria militar holandesa; a cidade em miniatura Madurodam foi construída em sua homenagem."
  },
  "grupo-e-curacao-05": {
    "nome": "Moises Frumencio da Costa Gomez",
    "pais": "Curaçao",
    "grupo": "Grupo E",
    "numero": 5,
    "posicao": "Lateral",
    "raridade": "Lendário",
    "periodo": "1907-1966",
    "resumo": "Político e líder do Partido Nacional do Povo.",
    "legado": "Considerado um dos pais fundadores das Antilhas Holandesas e pioneiro na luta pela autonomia política das ilhas."
  },
  "grupo-e-curacao-06": {
    "nome": "Elis Juliana",
    "pais": "Curaçao",
    "grupo": "Grupo E",
    "numero": 6,
    "posicao": "Volante",
    "raridade": "Comum",
    "periodo": "1927-2013",
    "resumo": "Antropólogo cultural, artista plástico, poeta e escritor em papiamento.",
    "legado": "Dedicou a vida a registrar e preservar o folclore, a história oral e as tradições autênticas da população afro-curaçauense."
  },
  "grupo-e-curacao-07": {
    "nome": "Cola Debrot",
    "pais": "Curaçao",
    "grupo": "Grupo E",
    "numero": 7,
    "posicao": "Meia",
    "raridade": "Épico",
    "periodo": "1902-1981",
    "resumo": "Escritor, médico e político que atuou como Governador das Antilhas Holandesas.",
    "legado": "Sua novela literária de estreia marcou o início formal da literatura moderna de Curaçao e das Antilhas."
  },
  "grupo-e-curacao-08": {
    "nome": "Boeli van Leeuwen",
    "pais": "Curaçao",
    "grupo": "Grupo E",
    "numero": 8,
    "posicao": "Meia",
    "raridade": "Comum",
    "periodo": "1922-2007",
    "resumo": "Renomado autor e poeta premiado em língua holandesa.",
    "legado": "Suas obras literárias exploram a complexa identidade caribenha, o colonialismo e o dilema existencial do homem das Antilhas."
  },
  "grupo-e-curacao-09": {
    "nome": "Pierre Lauffer",
    "pais": "Curaçao",
    "grupo": "Grupo E",
    "numero": 9,
    "posicao": "Ponta",
    "raridade": "Raro",
    "periodo": "1920-1981",
    "resumo": "Ativista cultural, poeta e promotor fundamental da língua local.",
    "legado": "Consagrado como o pai da literatura em Papiamento, elevou a língua local a uma forma de arte literária respeitada."
  },
  "grupo-e-curacao-10": {
    "nome": "Tula",
    "pais": "Curaçao",
    "grupo": "Grupo E",
    "numero": 10,
    "posicao": "Camisa 10",
    "raridade": "Comum",
    "periodo": "?-1795",
    "resumo": "Líder escravizado que encabeçou a grande Rebelião de Escravos de Curaçao de 1795.",
    "legado": "Herói nacional de Curaçao, sua luta pela liberdade e igualdade sob os ideais da Revolução Francesa tornou-se o principal símbolo de emancipação no país."
  },
  "grupo-e-curacao-11": {
    "nome": "Frank Martinus Arion",
    "pais": "Curaçao",
    "grupo": "Grupo E",
    "numero": 11,
    "posicao": "Centroavante",
    "raridade": "Comum",
    "periodo": "1936-2015",
    "resumo": "Autor, linguista e ativista da educação antilhana.",
    "legado": "Defendeu ferrenhamente o uso do papiamento como língua de instrução escolar, fundando a primeira instituição de ensino na língua nativa."
  },
  "grupo-e-curacao-12": {
    "nome": "Nilda Pinto",
    "pais": "Curaçao",
    "grupo": "Grupo E",
    "numero": 12,
    "posicao": "Técnica",
    "raridade": "Lendário",
    "periodo": "1918-1954",
    "resumo": "Professora, escritora de literatura infantil e radialista.",
    "legado": "Foi pioneira na criação e difusão de materiais educacionais infantis e livros de contos inteiramente em papiamento."
  },
  "grupo-e-equador-01": {
    "nome": "Eloy Alfaro",
    "pais": "Equador",
    "grupo": "Grupo E",
    "numero": 1,
    "posicao": "Goleiro",
    "raridade": "Lendário",
    "periodo": "1842-1912",
    "resumo": "Duas vezes presidente do Equador e líder máximo da Revolução Liberal Equatoriana.",
    "legado": "Instituiu a separação entre Igreja e Estado, modernizou o sistema legal, inaugurou ferrovias e promoveu os direitos civis."
  },
  "grupo-e-equador-02": {
    "nome": "Eugenio Espejo",
    "pais": "Equador",
    "grupo": "Grupo E",
    "numero": 2,
    "posicao": "Lateral",
    "raridade": "Comum",
    "periodo": "1747-1795",
    "resumo": "Médico, escritor e promotor das ideias iluministas na Real Audiência de Quito.",
    "legado": "Foi o precursor intelectual e primeiro inspirador do movimento de independência equatoriano."
  },
  "grupo-e-equador-03": {
    "nome": "Manuela Sáenz",
    "pais": "Equador",
    "grupo": "Grupo E",
    "numero": 3,
    "posicao": "Zagueira",
    "raridade": "Raro",
    "periodo": "1797-1856",
    "resumo": "Combatente política, espiã e figura crucial nas guerras de independência sul-americanas.",
    "legado": "Conhecida como \"A Libertadora do Libertador\" por ter salvo a vida de Simón Bolívar, é hoje símbolo do ativismo feminino na história continental."
  },
  "grupo-e-equador-04": {
    "nome": "Juan Montalvo",
    "pais": "Equador",
    "grupo": "Grupo E",
    "numero": 4,
    "posicao": "Zagueiro",
    "raridade": "Comum",
    "periodo": "1832-1889",
    "resumo": "Ensaísta, polemista ferrenho e defensor ardente do liberalismo.",
    "legado": "Suas obras foram a principal oposição intelectual a ditaduras na época; suas frases imortalizaram a luta contra a tirania no Equador."
  },
  "grupo-e-equador-05": {
    "nome": "Tránsito Amaguaña",
    "pais": "Equador",
    "grupo": "Grupo E",
    "numero": 5,
    "posicao": "Lateral",
    "raridade": "Lendário",
    "periodo": "1909-2009",
    "resumo": "Militante indígena incansável e fundadora dos primeiros sindicatos agrícolas no Equador.",
    "legado": "Liderou protestos exigindo o fim da servidão e terras para os indígenas, estabelecendo as bases para as escolas bilíngues no país."
  },
  "grupo-e-equador-06": {
    "nome": "Vicente Rocafuerte",
    "pais": "Equador",
    "grupo": "Grupo E",
    "numero": 6,
    "posicao": "Volante",
    "raridade": "Comum",
    "periodo": "1783-1847",
    "resumo": "Intelectual, diplomata e o segundo presidente da história do Equador.",
    "legado": "Famoso por organizar a nação recém-nascida sob princípios constitucionais rigorosos, priorizando a estabilidade civil e fundando o sistema educacional e militar."
  },
  "grupo-e-equador-07": {
    "nome": "Matilde Hidalgo",
    "pais": "Equador",
    "grupo": "Grupo E",
    "numero": 7,
    "posicao": "Meia",
    "raridade": "Épico",
    "periodo": "1889-1974",
    "resumo": "Médica, poeta e incansável ativista pelos direitos civis femininos no país.",
    "legado": "Foi a primeira mulher a exercer o direito ao voto no Equador e na América Latina (1924), bem como a primeira a obter um doutorado em medicina no país."
  },
  "grupo-e-equador-08": {
    "nome": "Oswaldo Guayasamín",
    "pais": "Equador",
    "grupo": "Grupo E",
    "numero": 8,
    "posicao": "Meia",
    "raridade": "Comum",
    "periodo": "1919-1999",
    "resumo": "Pintor, escultor e um dos mais famosos artistas plásticos da América do Sul.",
    "legado": "Sua obra monumental canalizou as dores, a desigualdade, a pobreza e a herança indígena da América Latina para uma arte expressionista inesquecível."
  },
  "grupo-e-equador-09": {
    "nome": "Julio Jaramillo",
    "pais": "Equador",
    "grupo": "Grupo E",
    "numero": 9,
    "posicao": "Ponta",
    "raridade": "Raro",
    "periodo": "1935-1978",
    "resumo": "Cantor e compositor idolatrado, conhecido como \"El Ruiseñor de América\" (O Rouxinol da América).",
    "legado": "Gravou mais de 4.000 canções e universalizou o gênero pasillo equatoriano, tornando-se uma lenda da música romântica em todo o continente espanhol."
  },
  "grupo-e-equador-10": {
    "nome": "Abdón Calderón",
    "pais": "Equador",
    "grupo": "Grupo E",
    "numero": 10,
    "posicao": "Camisa 10",
    "raridade": "Comum",
    "periodo": "1804-1822",
    "resumo": "Jovem militar elevado à condição de herói nacional após a Batalha de Pichincha.",
    "legado": "A lenda de sua bravura indomável mesmo após múltiplos ferimentos tornou-o o grande símbolo de patriotismo e heroísmo da juventude equatoriana."
  },
  "grupo-e-equador-11": {
    "nome": "Rumiñahui",
    "pais": "Equador",
    "grupo": "Grupo E",
    "numero": 11,
    "posicao": "Centroavante",
    "raridade": "Comum",
    "periodo": "?-1535",
    "resumo": "Feroz general inca que liderou a última grande resistência indígena contra as forças espanholas no Equador.",
    "legado": "Preferiu incendiar e destruir Quito a deixá-la nas mãos dos conquistadores, escondendo o tesouro do Império; é lembrado como o grande herói da resistência pré-colombiana."
  },
  "grupo-e-equador-12": {
    "nome": "Dolores Cacuango",
    "pais": "Equador",
    "grupo": "Grupo E",
    "numero": 12,
    "posicao": "Técnica",
    "raridade": "Lendário",
    "periodo": "1881-1971",
    "resumo": "Proeminente ativista e defensora ferrenha dos direitos humanos e territoriais do povo indígena.",
    "legado": "Em 1944, co-fundou a pioneira Federação Equatoriana de Índios (FEI) e estabeleceu a primeira rede clandestina de escolas bilíngues kichwa-espanhol do país."
  }
});
