window.FICHAS_TECNICAS = window.FICHAS_TECNICAS || {};
// Fichas técnicas - GRUPO-H
Object.assign(window.FICHAS_TECNICAS, {
  "grupo-h-arabia-saudita-01": {
    "nome": "Abdulaziz (Ibn Saud)",
    "pais": "Arábia Saudita",
    "grupo": "Grupo H",
    "numero": 1,
    "posicao": "Goleiro",
    "raridade": "Lendário",
    "periodo": "1875-1953",
    "resumo": "Fundador e primeiro monarca da moderna Arábia Saudita.",
    "legado": "Unificou as tribos da Península Arábica sob um único Estado e liderou o país durante a descoberta inicial de enormes reservas de petróleo."
  },
  "grupo-h-arabia-saudita-02": {
    "nome": "Muhammad ibn Abd al-Wahhab",
    "pais": "Arábia Saudita",
    "grupo": "Grupo H",
    "numero": 2,
    "posicao": "Lateral",
    "raridade": "Comum",
    "periodo": "1703-1792",
    "resumo": "Teólogo islâmico e reformador religioso.",
    "legado": "Formou um pacto histórico com a Casa de Saud, fundando o movimento wahhabita que se tornou a base ideológica e religiosa do país."
  },
  "grupo-h-arabia-saudita-03": {
    "nome": "Rei Faisal",
    "pais": "Arábia Saudita",
    "grupo": "Grupo H",
    "numero": 3,
    "posicao": "Zagueiro",
    "raridade": "Raro",
    "periodo": "1906-1975",
    "resumo": "Terceiro rei da Arábia Saudita (1964-1975).",
    "legado": "Conduziu a modernização do país, promoveu a educação (incluindo para meninas) e orquestrou o embargo de petróleo de 1973 que alterou a geopolítica global."
  },
  "grupo-h-arabia-saudita-04": {
    "nome": "Princesa Nourah bint Abdul Rahman",
    "pais": "Arábia Saudita",
    "grupo": "Grupo H",
    "numero": 4,
    "posicao": "Zagueira",
    "raridade": "Comum",
    "periodo": "1875-1950",
    "resumo": "Conselheira política de destaque e irmã do Rei Abdulaziz.",
    "legado": "Desempenhou um papel crucial nos bastidores durante a formação do reino, sendo um símbolo primitivo de liderança feminina na corte saudita."
  },
  "grupo-h-arabia-saudita-05": {
    "nome": "Rei Khaled",
    "pais": "Arábia Saudita",
    "grupo": "Grupo H",
    "numero": 5,
    "posicao": "Lateral",
    "raridade": "Lendário",
    "periodo": "1913-1982",
    "resumo": "Quarto rei da Arábia Saudita (1975-1982).",
    "legado": "Supervisionou um período de imenso desenvolvimento socioeconômico impulsionado pela riqueza do petróleo, focando na infraestrutura massiva e no bem-estar do Estado."
  },
  "grupo-h-arabia-saudita-06": {
    "nome": "Abdullah Tariki",
    "pais": "Arábia Saudita",
    "grupo": "Grupo H",
    "numero": 6,
    "posicao": "Volante",
    "raridade": "Comum",
    "periodo": "1919-1997",
    "resumo": "Primeiro Ministro do Petróleo saudita.",
    "legado": "Foi um dos visionários cofundadores da OPEP (Organização dos Países Exportadores de Petróleo), mudando permanentemente a economia global da energia."
  },
  "grupo-h-arabia-saudita-07": {
    "nome": "Ahmed Zaki Yamani",
    "pais": "Arábia Saudita",
    "grupo": "Grupo H",
    "numero": 7,
    "posicao": "Meia",
    "raridade": "Épico",
    "periodo": "1930-2021",
    "resumo": "Político de destaque e Ministro do Petróleo por mais de duas décadas.",
    "legado": "A face pública do poder energético árabe na década de 1970, foi o arquiteto da nacionalização progressiva da indústria do petróleo saudita."
  },
  "grupo-h-arabia-saudita-08": {
    "nome": "Tadj al-Hamavi",
    "pais": "Arábia Saudita",
    "grupo": "Grupo H",
    "numero": 8,
    "posicao": "Meia",
    "raridade": "Comum",
    "periodo": "~Século XII",
    "resumo": "Famoso historiador e intelectual.",
    "legado": "Suas compilações geográficas e enciclopédias da Península Arábica tornaram-se fontes inestimáveis para entender a história islâmica precoce."
  },
  "grupo-h-arabia-saudita-09": {
    "nome": "Fatima bint Ibrahim",
    "pais": "Arábia Saudita",
    "grupo": "Grupo H",
    "numero": 9,
    "posicao": "Ponta",
    "raridade": "Raro",
    "periodo": "Século XIII/XIV",
    "resumo": "Reverenciada acadêmica e teóloga islâmica em Meca.",
    "legado": "Foi uma das mais respeitadas contadoras de Hadiths (tradições do profeta), atraindo estudantes do mundo islâmico inteiro para suas aulas."
  },
  "grupo-h-arabia-saudita-10": {
    "nome": "Rei Abdullah",
    "pais": "Arábia Saudita",
    "grupo": "Grupo H",
    "numero": 10,
    "posicao": "Camisa 10",
    "raridade": "Comum",
    "periodo": "1924-2015",
    "resumo": "Sexto rei da Arábia Saudita.",
    "legado": "Promoveu reformas cautelosas de modernização, incluindo bolsas de estudo no exterior e concessão gradual de mais direitos cívicos às mulheres."
  },
  "grupo-h-arabia-saudita-11": {
    "nome": "Al-Asma'i",
    "pais": "Arábia Saudita",
    "grupo": "Grupo H",
    "numero": 11,
    "posicao": "Centroavante",
    "raridade": "Comum",
    "periodo": "740-828",
    "resumo": "Pioneiro filólogo, zoólogo e botânico árabe inicial.",
    "legado": "Seu trabalho de compilar o folclore beduíno, poesia e ciência animal lançou os alicerces da história natural e da literatura árabe clássica."
  },
  "grupo-h-arabia-saudita-12": {
    "nome": "Ghazi Al-Gosaibi",
    "pais": "Arábia Saudita",
    "grupo": "Grupo H",
    "numero": 12,
    "posicao": "Técnico",
    "raridade": "Lendário",
    "periodo": "1940-2010",
    "resumo": "Político de alto escalão, embaixador e aclamado escritor.",
    "legado": "Voz do liberalismo e modernidade, usou a sua influência ministerial e os seus romances populares para promover a tolerância e criticar o extremismo."
  },
  "grupo-h-cabo-verde-01": {
    "nome": "Amílcar Cabral",
    "pais": "Cabo Verde",
    "grupo": "Grupo H",
    "numero": 1,
    "posicao": "Goleiro",
    "raridade": "Lendário",
    "periodo": "1924-1973",
    "resumo": "Herói da independência e teórico anticolonial.",
    "legado": "Fundou o PAIGC, unindo Cabo Verde e a Guiné-Bissau numa luta armada bem-sucedida contra o colonialismo português; os seus escritos inspiraram movimentos em toda a África."
  },
  "grupo-h-cabo-verde-02": {
    "nome": "Cesária Évora",
    "pais": "Cabo Verde",
    "grupo": "Grupo H",
    "numero": 2,
    "posicao": "Lateral",
    "raridade": "Comum",
    "periodo": "1941-2011",
    "resumo": "A \"Rainha da Morna\", cantora internacionalmente aclamada.",
    "legado": "Com a sua voz melancólica e a tradição de cantar descalça, colocou a cultura e a música de Cabo Verde no mapa global, vencendo um Grammy."
  },
  "grupo-h-cabo-verde-03": {
    "nome": "Aristides Pereira",
    "pais": "Cabo Verde",
    "grupo": "Grupo H",
    "numero": 3,
    "posicao": "Zagueiro",
    "raridade": "Raro",
    "periodo": "1923-2011",
    "resumo": "Combatente da liberdade e o primeiro Presidente de Cabo Verde.",
    "legado": "Assumiu o controle do PAIGC após a morte de Cabral, supervisionando a transição pacífica para a independência e governando o país nas suas primeiras décadas formativas."
  },
  "grupo-h-cabo-verde-04": {
    "nome": "Eugénio Tavares",
    "pais": "Cabo Verde",
    "grupo": "Grupo H",
    "numero": 4,
    "posicao": "Zagueiro",
    "raridade": "Comum",
    "periodo": "1867-1930",
    "resumo": "Poeta, jornalista e compositor nativo da ilha Brava.",
    "legado": "É considerado o verdadeiro pai da \"Morna\" cabo-verdiana, usando o crioulo como língua literária para expressar o sofrimento e a saudade do seu povo."
  },
  "grupo-h-cabo-verde-05": {
    "nome": "Baltasar Lopes da Silva",
    "pais": "Cabo Verde",
    "grupo": "Grupo H",
    "numero": 5,
    "posicao": "Lateral",
    "raridade": "Lendário",
    "periodo": "1907-1989",
    "resumo": "Escritor, filólogo e figura central da literatura do país.",
    "legado": "Co-fundador da emblemática revista \"Claridade\" e autor de \"Chiquinho\", o romance que deu origem e identidade à literatura nacional de Cabo Verde."
  },
  "grupo-h-cabo-verde-06": {
    "nome": "Jorge Barbosa",
    "pais": "Cabo Verde",
    "grupo": "Grupo H",
    "numero": 6,
    "posicao": "Volante",
    "raridade": "Comum",
    "periodo": "1902-1971",
    "resumo": "Poeta proeminente e co-fundador do Movimento Claridoso.",
    "legado": "Rompeu com os moldes literários coloniais portugueses, introduzindo nas suas poesias temas do quotidiano das ilhas, a seca e o dilema da emigração."
  },
  "grupo-h-cabo-verde-07": {
    "nome": "Manuel Lopes",
    "pais": "Cabo Verde",
    "grupo": "Grupo H",
    "numero": 7,
    "posicao": "Meia",
    "raridade": "Épico",
    "periodo": "1907-2005",
    "resumo": "Poeta, romancista e pilar da revista literária \"Claridade\".",
    "legado": "Com obras aclamadas como \"Os Flagelados do Vento Leste\", expôs a dura realidade das fomes cíclicas e da sobrevivência camponesa nas ilhas."
  },
  "grupo-h-cabo-verde-08": {
    "nome": "Pedro Pires",
    "pais": "Cabo Verde",
    "grupo": "Grupo H",
    "numero": 8,
    "posicao": "Meia",
    "raridade": "Comum",
    "periodo": "1934-presente",
    "resumo": "Antigo combatente, Primeiro-Ministro e Presidente.",
    "legado": "Foi fundamental no desenvolvimento democrático de Cabo Verde; galardoado com o Prémio Ibrahim de Liderança Africana de Excelência devido à sua governação transparente."
  },
  "grupo-h-cabo-verde-09": {
    "nome": "Ildo Lobo",
    "pais": "Cabo Verde",
    "grupo": "Grupo H",
    "numero": 9,
    "posicao": "Ponta",
    "raridade": "Raro",
    "periodo": "1953-2004",
    "resumo": "Lendário cantor de intervenção e vocalista d'Os Tubarões.",
    "legado": "A sua voz tornou-se a trilha sonora oficial da independência e da transição para o multipartidarismo, lutando politicamente através do Funaná e da Morna."
  },
  "grupo-h-cabo-verde-10": {
    "nome": "Bana",
    "pais": "Cabo Verde",
    "grupo": "Grupo H",
    "numero": 10,
    "posicao": "Camisa 10",
    "raridade": "Comum",
    "periodo": "1932-2013",
    "resumo": "Cantor pioneiro, frequentemente chamado \"Rei da Morna\".",
    "legado": "Um embaixador cultural vital que levou a música de Cabo Verde para a Europa através da emigração, abrindo as portas do mercado para artistas como Cesária Évora."
  },
  "grupo-h-cabo-verde-11": {
    "nome": "António Aurélio Gonçalves",
    "pais": "Cabo Verde",
    "grupo": "Grupo H",
    "numero": 11,
    "posicao": "Centroavante",
    "raridade": "Comum",
    "periodo": "1901-1984",
    "resumo": "Distinto professor, ensaísta e romancista.",
    "legado": "Pintou um retrato psicológico detalhado das mulheres de São Vicente e da vida na cidade do Mindelo através das suas narrativas e contos clássicos."
  },
  "grupo-h-cabo-verde-12": {
    "nome": "Roberto Duarte Silva",
    "pais": "Cabo Verde",
    "grupo": "Grupo H",
    "numero": 12,
    "posicao": "Técnico",
    "raridade": "Lendário",
    "periodo": "1837-1889",
    "resumo": "Renomado cientista químico que construiu a sua carreira na França.",
    "legado": "Um investigador respeitado mundialmente cujas descobertas na química orgânica, incluindo derivados do álcool, lhe valeram a presidência da prestigiada Sociedade Química de Paris."
  },
  "grupo-h-espanha-01": {
    "nome": "Isabel de Castela",
    "pais": "Espanha",
    "grupo": "Grupo H",
    "numero": 1,
    "posicao": "Goleira",
    "raridade": "Lendário",
    "periodo": "1451-1504",
    "resumo": "Rainha de Castela e \"Rainha Católica\".",
    "legado": "A sua união com Fernando de Aragão formou a Espanha moderna; patrocinou a viagem de Cristóvão Colombo em 1492, alterando a história mundial para sempre."
  },
  "grupo-h-espanha-02": {
    "nome": "Miguel de Cervantes",
    "pais": "Espanha",
    "grupo": "Grupo H",
    "numero": 2,
    "posicao": "Lateral",
    "raridade": "Comum",
    "periodo": "1547-1616",
    "resumo": "Soldado e maior escritor da língua espanhola.",
    "legado": "Autor de \"Dom Quixote\", aclamado como o primeiro romance moderno do mundo e um marco absoluto da literatura ocidental."
  },
  "grupo-h-espanha-03": {
    "nome": "Pablo Picasso",
    "pais": "Espanha",
    "grupo": "Grupo H",
    "numero": 3,
    "posicao": "Zagueiro",
    "raridade": "Raro",
    "periodo": "1881-1973",
    "resumo": "Pintor, escultor e pioneiro modernista.",
    "legado": "Co-fundador do Cubismo, o seu trabalho radical e pinturas como \"Guernica\" redefiniram a arte visual do século XX."
  },
  "grupo-h-espanha-04": {
    "nome": "Diego Velázquez",
    "pais": "Espanha",
    "grupo": "Grupo H",
    "numero": 4,
    "posicao": "Zagueiro",
    "raridade": "Comum",
    "periodo": "1599-1660",
    "resumo": "Artista principal da corte do Rei Filipe IV e expoente máximo do Século de Ouro Espanhol.",
    "legado": "A sua obra-prima \"As Meninas\" é uma das pinturas mais analisadas e brilhantes da história da arte realista."
  },
  "grupo-h-espanha-05": {
    "nome": "Federico García Lorca",
    "pais": "Espanha",
    "grupo": "Grupo H",
    "numero": 5,
    "posicao": "Lateral",
    "raridade": "Lendário",
    "periodo": "1898-1936",
    "resumo": "Poeta e dramaturgo de vanguarda da Geração de 27.",
    "legado": "Fundiu a tradição flamenca com o surrealismo; o seu trágico assassinato no início da Guerra Civil tornou-o um símbolo atemporal da liberdade e da arte antifascista."
  },
  "grupo-h-espanha-06": {
    "nome": "Santiago Ramón y Cajal",
    "pais": "Espanha",
    "grupo": "Grupo H",
    "numero": 6,
    "posicao": "Volante",
    "raridade": "Comum",
    "periodo": "1852-1934",
    "resumo": "Cientista pioneiro e ganhador do Nobel de Medicina.",
    "legado": "Considerado o \"pai da neurociência moderna\", mapeou microscopicamente o cérebro humano provando que o sistema nervoso é composto por células individuais (neurônios)."
  },
  "grupo-h-espanha-07": {
    "nome": "Salvador Dalí",
    "pais": "Espanha",
    "grupo": "Grupo H",
    "numero": 7,
    "posicao": "Meia",
    "raridade": "Épico",
    "periodo": "1904-1989",
    "resumo": "Gênio da pintura e figura excêntrica proeminente.",
    "legado": "O maior expoente do surrealismo, materializou o subconsciente, os sonhos e o tempo derretido (A Persistência da Memória) na tela."
  },
  "grupo-h-espanha-08": {
    "nome": "Antoni Gaudí",
    "pais": "Espanha",
    "grupo": "Grupo H",
    "numero": 8,
    "posicao": "Meia",
    "raridade": "Comum",
    "periodo": "1852-1926",
    "resumo": "Arquiteto inovador ligado ao modernismo catalão.",
    "legado": "Desenhou a icônica Sagrada Família em Barcelona, misturando formas orgânicas da natureza e um sistema geométrico sem precedentes."
  },
  "grupo-h-espanha-09": {
    "nome": "Francisco Goya",
    "pais": "Espanha",
    "grupo": "Grupo H",
    "numero": 9,
    "posicao": "Ponta",
    "raridade": "Raro",
    "periodo": "1746-1828",
    "resumo": "Pintor romântico e cronista implacável do seu tempo.",
    "legado": "O \"Pai da Arte Moderna\", os seus quadros (como o violento \"Três de Maio de 1808\" e as Pinturas Negras) refletiram o puro terror da guerra e a degradação humana."
  },
  "grupo-h-espanha-10": {
    "nome": "El Cid (Rodrigo Díaz de Vivar)",
    "pais": "Espanha",
    "grupo": "Grupo H",
    "numero": 10,
    "posicao": "Camisa 10",
    "raridade": "Comum",
    "periodo": "~1043-1099",
    "resumo": "Cavaleiro, estrategista militar e líder mercenário da Reconquista.",
    "legado": "Herói nacional por excelência no épico medieval espanhol, dominou o leste da Península Ibérica, capturando Valência dos mouros."
  },
  "grupo-h-espanha-11": {
    "nome": "Rosalía de Castro",
    "pais": "Espanha",
    "grupo": "Grupo H",
    "numero": 11,
    "posicao": "Centroavante",
    "raridade": "Comum",
    "periodo": "1837-1885",
    "resumo": "Escritora romântica e figura central do ressurgimento cultural galego (Rexurdimento).",
    "legado": "Defensora dos marginalizados e da mulher, as suas poesias restauraram a dignidade e a legitimidade literária da língua galega."
  },
  "grupo-h-espanha-12": {
    "nome": "Clara Campoamor",
    "pais": "Espanha",
    "grupo": "Grupo H",
    "numero": 12,
    "posicao": "Técnica",
    "raridade": "Lendário",
    "periodo": "1888-1972",
    "resumo": "Política pioneira, advogada e sufragista incansável.",
    "legado": "A figura principal que argumentou com sucesso e conquistou o direito de voto para as mulheres na Constituição Espanhola de 1931 durante a Segunda República."
  },
  "grupo-h-uruguai-01": {
    "nome": "José Gervasio Artigas",
    "pais": "Uruguai",
    "grupo": "Grupo H",
    "numero": 1,
    "posicao": "Goleiro",
    "raridade": "Lendário",
    "periodo": "1764-1850",
    "resumo": "Líder militar e máximo estadista da revolução da Banda Oriental.",
    "legado": "Venerado como o Herói Nacional e \"Pai da Nação\" uruguaia, defendeu um modelo republicano ferozmente descentralizado e igualitário na América do Sul."
  },
  "grupo-h-uruguai-02": {
    "nome": "José Batlle y Ordóñez",
    "pais": "Uruguai",
    "grupo": "Grupo H",
    "numero": 2,
    "posicao": "Lateral",
    "raridade": "Comum",
    "periodo": "1856-1929",
    "resumo": "Jornalista e Presidente que cumpriu dois mandatos transformadores.",
    "legado": "O arquiteto do \"Estado de Bem-Estar\" moderno; introduziu pioneiramente na América Latina a jornada de oito horas, o sufrágio feminino e a secularização."
  },
  "grupo-h-uruguai-03": {
    "nome": "Eduardo Galeano",
    "pais": "Uruguai",
    "grupo": "Grupo H",
    "numero": 3,
    "posicao": "Zagueiro",
    "raridade": "Raro",
    "periodo": "1940-2015",
    "resumo": "Ensaísta, jornalista militante e romancista.",
    "legado": "Autor do icônico \"As Veias Abertas da América Latina\", dissecando com maestria os efeitos do colonialismo e imperialismo no continente."
  },
  "grupo-h-uruguai-04": {
    "nome": "Mario Benedetti",
    "pais": "Uruguai",
    "grupo": "Grupo H",
    "numero": 4,
    "posicao": "Zagueiro",
    "raridade": "Comum",
    "periodo": "1920-2009",
    "resumo": "Um dos escritores sul-americanos mais lidos do século XX.",
    "legado": "Poeta e romancista central da \"Geração de 45\", capturou as emoções e a identidade da classe média de Montevidéu, bem como o trauma do exílio."
  },
  "grupo-h-uruguai-05": {
    "nome": "Juana de Ibarbourou",
    "pais": "Uruguai",
    "grupo": "Grupo H",
    "numero": 5,
    "posicao": "Lateral",
    "raridade": "Lendário",
    "periodo": "1892-1979",
    "resumo": "Aclamada internacionalmente como \"Juana de América\".",
    "legado": "Uma das poetisas mais reverenciadas da literatura de língua espanhola; seus versos transbordam vitalidade e paixão sensual através da natureza."
  },
  "grupo-h-uruguai-06": {
    "nome": "Horacio Quiroga",
    "pais": "Uruguai",
    "grupo": "Grupo H",
    "numero": 6,
    "posicao": "Volante",
    "raridade": "Comum",
    "periodo": "1878-1937",
    "resumo": "Mestre supremo do conto curto de horror e natureza.",
    "legado": "Famoso por \"Cuentos de la Selva\", influenciou gerações com o seu estilo literário brutal onde o ser humano luta em vão contra a força da selva sul-americana."
  },
  "grupo-h-uruguai-07": {
    "nome": "Joaquín Torres García",
    "pais": "Uruguai",
    "grupo": "Grupo H",
    "numero": 7,
    "posicao": "Meia",
    "raridade": "Épico",
    "periodo": "1874-1949",
    "resumo": "Artista plástico, construtivista e professor.",
    "legado": "Famoso por desenhar o mapa invertido da América do Sul (\"O Nosso Norte é o Sul\"), redefinindo completamente a identidade visual e artística do continente."
  },
  "grupo-h-uruguai-08": {
    "nome": "Pedro Figari",
    "pais": "Uruguai",
    "grupo": "Grupo H",
    "numero": 8,
    "posicao": "Meia",
    "raridade": "Comum",
    "periodo": "1861-1938",
    "resumo": "Pintor modernista, advogado de defesa, filósofo e educador.",
    "legado": "Começou a pintar na velhice, celebrando cenas autênticas do Candombe afro-uruguaio e do gaúcho, preservando na tela a herança folclórica do país."
  },
  "grupo-h-uruguai-09": {
    "nome": "Juan Antonio Lavalleja",
    "pais": "Uruguai",
    "grupo": "Grupo H",
    "numero": 9,
    "posicao": "Ponta",
    "raridade": "Raro",
    "periodo": "1784-1853",
    "resumo": "Feroz líder revolucionário.",
    "legado": "Encabeçou os \"Trinta e Três Orientais\" que cruzaram o rio em 1825 para lutar contra o Império do Brasil, jurando o lema \"Liberdade ou Morte\"."
  },
  "grupo-h-uruguai-10": {
    "nome": "Fructuoso Rivera",
    "pais": "Uruguai",
    "grupo": "Grupo H",
    "numero": 10,
    "posicao": "Camisa 10",
    "raridade": "Comum",
    "periodo": "1784-1854",
    "resumo": "General militar e o primeiro Presidente Constitucional do Uruguai.",
    "legado": "Uma figura polarizadora e central da política precoce; fundou o tradicional Partido Colorado e teve um papel fundamental (e violento) nas guerras civis da nação."
  },
  "grupo-h-uruguai-11": {
    "nome": "Delmira Agustini",
    "pais": "Uruguai",
    "grupo": "Grupo H",
    "numero": 11,
    "posicao": "Centroavante",
    "raridade": "Comum",
    "periodo": "1886-1914",
    "resumo": "Poetisa modernista brilhante e precursora.",
    "legado": "Chocou e fascinou a sociedade do início do século XX ao escrever abertamente sobre a sexualidade feminina a partir do seu próprio ponto de vista poético e erótico."
  },
  "grupo-h-uruguai-12": {
    "nome": "China Zorrilla",
    "pais": "Uruguai",
    "grupo": "Grupo H",
    "numero": 12,
    "posicao": "Técnica",
    "raridade": "Lendário",
    "periodo": "1922-2014",
    "resumo": "Atriz, comediante e diretora formidável.",
    "legado": "Um ícone absoluto e amado da cultura rioplatense (Uruguai e Argentina), que dominou o teatro, o cinema e a televisão durante sete décadas."
  }
});
