window.FICHAS_TECNICAS = window.FICHAS_TECNICAS || {};
// Fichas técnicas - GRUPO-D
Object.assign(window.FICHAS_TECNICAS, {
  "grupo-d-australia-01": {
    "nome": "James Cook",
    "pais": "Austrália",
    "grupo": "Grupo D",
    "numero": 1,
    "posicao": "Goleiro",
    "raridade": "Épico",
    "periodo": "1728-1779",
    "resumo": "Capitão da Marinha Real Britânica, navegador e explorador.",
    "legado": "Liderou a primeira expedição europeia a mapear a costa leste da Austrália, abrindo caminho para o estabelecimento do país moderno."
  },
  "grupo-d-australia-02": {
    "nome": "Ned Kelly",
    "pais": "Austrália",
    "grupo": "Grupo D",
    "numero": 2,
    "posicao": "Lateral",
    "raridade": "Lendário",
    "periodo": "1854-1880",
    "resumo": "O mais infame \"bushranger\" (fora-da-lei) australiano, famoso por usar uma armadura de metal artesanal.",
    "legado": "Uma figura altamente polarizadora, visto por muitos como um símbolo de resistência da classe trabalhadora contra as autoridades coloniais opressoras."
  },
  "grupo-d-australia-03": {
    "nome": "Edmund Barton",
    "pais": "Austrália",
    "grupo": "Grupo D",
    "numero": 3,
    "posicao": "Zagueiro",
    "raridade": "Lendário",
    "periodo": "1849-1920",
    "resumo": "Político e juiz que foi um dos líderes do movimento para federar as colónias australianas.",
    "legado": "Tornou-se o primeiro Primeiro-Ministro da Austrália unificada e ajudou a redigir a constituição nacional."
  },
  "grupo-d-australia-04": {
    "nome": "John Monash",
    "pais": "Austrália",
    "grupo": "Grupo D",
    "numero": 4,
    "posicao": "Zagueiro",
    "raridade": "Épico",
    "periodo": "1865-1931",
    "resumo": "Engenheiro civil que se tornou comandante militar durante a Primeira Guerra Mundial.",
    "legado": "Considerado um dos mais brilhantes generais aliados do conflito, conhecido por táticas inovadoras que minimizaram perdas e garantiram vitórias cruciais."
  },
  "grupo-d-australia-05": {
    "nome": "Vincent Lingiari",
    "pais": "Austrália",
    "grupo": "Grupo D",
    "numero": 5,
    "posicao": "Lateral",
    "raridade": "Épico",
    "periodo": "1919-1988",
    "resumo": "Líder aborígene da etnia Gurindji e ativista dos direitos civis.",
    "legado": "Liderou a famosa greve de Wave Hill, um momento decisivo que levou ao reconhecimento dos direitos tradicionais à terra para as populações indígenas australianas."
  },
  "grupo-d-australia-06": {
    "nome": "Howard Florey",
    "pais": "Austrália",
    "grupo": "Grupo D",
    "numero": 6,
    "posicao": "Volante",
    "raridade": "Lendário",
    "periodo": "1898-1968",
    "resumo": "Farmacologista e patologista brilhante.",
    "legado": "Venceu o Prémio Nobel por liderar a equipa que desenvolveu e extraiu a penicilina para uso clínico, salvando milhões de vidas em todo o mundo."
  },
  "grupo-d-australia-07": {
    "nome": "Banjo Paterson",
    "pais": "Austrália",
    "grupo": "Grupo D",
    "numero": 7,
    "posicao": "Meia",
    "raridade": "Épico",
    "periodo": "1864-1941",
    "resumo": "Jornalista, autor e um dos poetas mais célebres do país.",
    "legado": "Escreveu \"Waltzing Matilda\" e \"The Man from Snowy River\", obras que capturaram a essência e o espírito do interior (outback) australiano."
  },
  "grupo-d-australia-08": {
    "nome": "Edith Cowan",
    "pais": "Austrália",
    "grupo": "Grupo D",
    "numero": 8,
    "posicao": "Meia",
    "raridade": "Raro",
    "periodo": "1861-1932",
    "resumo": "Pioneira dos direitos das mulheres e ativista social incansável.",
    "legado": "Fez história ao tornar-se a primeira mulher a ser eleita para um parlamento australiano, lutando pelos direitos das crianças e da família."
  },
  "grupo-d-australia-09": {
    "nome": "Nancy Bird Walton",
    "pais": "Austrália",
    "grupo": "Grupo D",
    "numero": 9,
    "posicao": "Ponta",
    "raridade": "Raro",
    "periodo": "1915-2009",
    "resumo": "Pioneira da aviação e a mulher mais jovem a obter uma licença comercial no Império Britânico.",
    "legado": "Fundou a Associação de Mulheres Pilotos da Austrália e dedicou a sua vida a promover a presença feminina nos céus."
  },
  "grupo-d-australia-10": {
    "nome": "Steve Irwin",
    "pais": "Austrália",
    "grupo": "Grupo D",
    "numero": 10,
    "posicao": "Camisa 10",
    "raridade": "Lendário",
    "periodo": "1962-2006",
    "resumo": "Especialista em vida selvagem, conservacionista e estrela de televisão reconhecida mundialmente.",
    "legado": "O carismático \"Caçador de Crocodilos\" educou e inspirou uma geração inteira sobre a importância da conservação animal."
  },
  "grupo-d-australia-11": {
    "nome": "Oodgeroo Noonuccal",
    "pais": "Austrália",
    "grupo": "Grupo D",
    "numero": 11,
    "posicao": "Centroavante",
    "raridade": "Épico",
    "periodo": "1920-1993",
    "resumo": "Poeta, educadora e incansável ativista política aborígene.",
    "legado": "Foi a primeira australiana indígena a publicar um livro de poesia, dando uma voz poderosa à luta pela igualdade e direitos à terra."
  },
  "grupo-d-australia-12": {
    "nome": "Mary MacKillop",
    "pais": "Austrália",
    "grupo": "Grupo D",
    "numero": 12,
    "posicao": "Técnica",
    "raridade": "Raro",
    "periodo": "1842-1909",
    "resumo": "Freira e educadora profundamente dedicada aos pobres e isolados.",
    "legado": "Fundou as Irmãs de São José do Sagrado Coração, criando dezenas de escolas e orfanatos; é a primeira e única santa australiana."
  },
  "grupo-d-estados-unidos-01": {
    "nome": "Abraham Lincoln",
    "pais": "Estados Unidos",
    "grupo": "Grupo D",
    "numero": 1,
    "posicao": "Lateral",
    "raridade": "Lendário",
    "periodo": "1809-1865",
    "resumo": "16º presidente americano, liderou o país durante a Guerra Civil e preservou a união da federação.",
    "legado": "Autor da Proclamação de Emancipação, que deu o passo decisivo para a abolição da escravatura no país."
  },
  "grupo-d-estados-unidos-02": {
    "nome": "Alexander Hamilton",
    "pais": "Estados Unidos",
    "grupo": "Grupo D",
    "numero": 2,
    "posicao": "Centroavante",
    "raridade": "Raro",
    "periodo": "1755-1804",
    "resumo": "O primeiro Secretário do Tesouro dos EUA e o principal autor de \"The Federalist Papers\".",
    "legado": "Arquiteto do sistema financeiro americano e defensor de um governo federal forte e moderno."
  },
  "grupo-d-estados-unidos-03": {
    "nome": "Benjamin Franklin",
    "pais": "Estados Unidos",
    "grupo": "Grupo D",
    "numero": 3,
    "posicao": "Zagueiro",
    "raridade": "Épico",
    "periodo": "1706-1790",
    "resumo": "Polímata, inventor e diplomata fundamental na negociação da aliança francesa durante a revolução.",
    "legado": "Contribuiu para a ciência com estudos sobre eletricidade e ajudou a redigir tanto a Declaração de Independência quanto a Constituição."
  },
  "grupo-d-estados-unidos-04": {
    "nome": "Eleanor Roosevelt",
    "pais": "Estados Unidos",
    "grupo": "Grupo D",
    "numero": 4,
    "posicao": "Técnica",
    "raridade": "Épico",
    "periodo": "1884-1962",
    "resumo": "Primeira-dama e diplomata que presidiu à comissão que redigiu a Declaração Universal dos Direitos Humanos na ONU.",
    "legado": "Transformou o papel da primeira-dama numa posição de ativismo político e social em prol dos marginalizados."
  },
  "grupo-d-estados-unidos-05": {
    "nome": "Frederick Douglass",
    "pais": "Estados Unidos",
    "grupo": "Grupo D",
    "numero": 5,
    "posicao": "Lateral",
    "raridade": "Raro",
    "periodo": "1818-1895",
    "resumo": "Ex-escravizado que se tornou num dos maiores líderes abolicionistas, oradores e escritores da história americana.",
    "legado": "Provou que a inteligência e a dignidade humana não dependem da raça, dedicando a vida à luta pela igualdade de direitos."
  },
  "grupo-d-estados-unidos-06": {
    "nome": "Harriet Tubman",
    "pais": "Estados Unidos",
    "grupo": "Grupo D",
    "numero": 6,
    "posicao": "Volante",
    "raridade": "Raro",
    "periodo": "1822-1913",
    "resumo": "Heroína da \"Underground Railroad\", realizou diversas missões perigosas para libertar pessoas escravizadas.",
    "legado": "Símbolo inabalável de coragem e resistência, atuou também como espiã para a União durante a Guerra Civil."
  },
  "grupo-d-estados-unidos-07": {
    "nome": "Martin Luther King Jr.",
    "pais": "Estados Unidos",
    "grupo": "Grupo D",
    "numero": 7,
    "posicao": "Meia",
    "raridade": "Lendário",
    "periodo": "1929-1968",
    "resumo": "Pastor e principal líder do movimento pelos direitos civis através da resistência não violenta.",
    "legado": "O seu discurso \"I Have a Dream\" e a sua luta levaram à aprovação da Lei dos Direitos Civis de 1964."
  },
  "grupo-d-estados-unidos-08": {
    "nome": "Rosa Parks",
    "pais": "Estados Unidos",
    "grupo": "Grupo D",
    "numero": 8,
    "posicao": "Meia",
    "raridade": "Épico",
    "periodo": "1913-2005",
    "resumo": "Ativista que se recusou a ceder o seu lugar num autocarro em Montgomery, iniciando um boicote histórico.",
    "legado": "Conhecida como a \"Mãe do Movimento pelos Direitos Civis\", o seu gesto foi um catalisador para o fim da segregação racial legal."
  },
  "grupo-d-estados-unidos-09": {
    "nome": "Susan B. Anthony",
    "pais": "Estados Unidos",
    "grupo": "Grupo D",
    "numero": 9,
    "posicao": "Ponta",
    "raridade": "Raro",
    "periodo": "1820-1906",
    "resumo": "Figura central no movimento pelo sufrágio feminino, lutando décadas pelo direito de voto das mulheres.",
    "legado": "Embora tenha morrido antes, o seu trabalho pavimentou o caminho para a 19ª Emenda à Constituição americana."
  },
  "grupo-d-estados-unidos-10": {
    "nome": "Thomas Edison",
    "pais": "Estados Unidos",
    "grupo": "Grupo D",
    "numero": 10,
    "posicao": "Camisa 10",
    "raridade": "Épico",
    "periodo": "1847-1931",
    "resumo": "Inventor prolífico que registou mais de mil patentes, incluindo a lâmpada incandescente e o fonógrafo.",
    "legado": "Revolucionou a vida moderna através do desenvolvimento da distribuição de energia elétrica e do cinema."
  },
  "grupo-d-estados-unidos-11": {
    "nome": "Thomas Jefferson",
    "pais": "Estados Unidos",
    "grupo": "Grupo D",
    "numero": 11,
    "posicao": "Zagueiro",
    "raridade": "Épico",
    "periodo": "1743-1826",
    "resumo": "O principal autor da Declaração de Independência dos Estados Unidos e o terceiro presidente da nação.",
    "legado": "Um fervoroso defensor dos ideais iluministas de liberdade individual e separação entre Igreja e Estado."
  },
  "grupo-d-estados-unidos-12": {
    "nome": "George Washington",
    "pais": "Estados Unidos",
    "grupo": "Grupo D",
    "numero": 12,
    "posicao": "Goleiro",
    "raridade": "Lendário",
    "periodo": "1732-1799",
    "resumo": "Comandante em chefe do Exército Continental na Guerra da Independência e o primeiro presidente dos Estados Unidos.",
    "legado": "Considerado o \"Pai da Pátria\", estabeleceu as bases da democracia americana e a tradição da transição pacífica de poder."
  },
  "grupo-d-paraguai-01": {
    "nome": "José Gaspar Rodríguez de Francia",
    "pais": "Paraguai",
    "grupo": "Grupo D",
    "numero": 1,
    "posicao": "Goleiro",
    "raridade": "Lendário",
    "periodo": "1766-1840",
    "resumo": "Conhecido como \"El Supremo\", foi o primeiro líder do Paraguai independente.",
    "legado": "Isolou o país para proteger sua independência e soberania frente aos vizinhos, promovendo uma rígida autossuficiência econômica."
  },
  "grupo-d-paraguai-02": {
    "nome": "Carlos Antonio López",
    "pais": "Paraguai",
    "grupo": "Grupo D",
    "numero": 2,
    "posicao": "Lateral",
    "raridade": "Épico",
    "periodo": "1792-1862",
    "resumo": "Primeiro presidente constitucional do Paraguai, responsável por encerrar o isolamento ditado por Francia.",
    "legado": "Modernizou o país introduzindo estradas de ferro, telégrafos, fundições e estaleiros, além de enviar estudantes à Europa."
  },
  "grupo-d-paraguai-03": {
    "nome": "Francisco Solano López",
    "pais": "Paraguai",
    "grupo": "Grupo D",
    "numero": 3,
    "posicao": "Zagueiro",
    "raridade": "Lendário",
    "periodo": "1827-1870",
    "resumo": "Presidente e marechal durante a trágica Guerra da Tríplice Aliança (Guerra do Paraguai).",
    "legado": "Uma figura histórica complexa; é reverenciado no Paraguai como o herói máximo que resistiu e morreu defendendo a nação até o fim."
  },
  "grupo-d-paraguai-04": {
    "nome": "Fulgencio Yegros",
    "pais": "Paraguai",
    "grupo": "Grupo D",
    "numero": 4,
    "posicao": "Zagueiro",
    "raridade": "Raro",
    "periodo": "1780-1821",
    "resumo": "Militar e herói da independência paraguaia, atuou como o primeiro chefe de estado (Cônsul) do país recém-liberto.",
    "legado": "Peça central na Revolução de Maio de 1811, que libertou o Paraguai do domínio espanhol de forma pacífica."
  },
  "grupo-d-paraguai-05": {
    "nome": "Pedro Juan Caballero",
    "pais": "Paraguai",
    "grupo": "Grupo D",
    "numero": 5,
    "posicao": "Lateral",
    "raridade": "Épico",
    "periodo": "1786-1821",
    "resumo": "Importante líder político e militar, companheiro inseparável de Yegros na gesta da independência.",
    "legado": "Liderou ativamente a conspiração militar contra o domínio espanhol e foi signatário do bando de independência."
  },
  "grupo-d-paraguai-06": {
    "nome": "Augusto Roa Bastos",
    "pais": "Paraguai",
    "grupo": "Grupo D",
    "numero": 6,
    "posicao": "Volante",
    "raridade": "Lendário",
    "periodo": "1917-2005",
    "resumo": "O maior romancista paraguaio e um dos grandes expoentes da literatura latino-americana, vencedor do Prêmio Cervantes.",
    "legado": "Imortalizou a complexa história e a cultura do povo guarani através de obras-primas como \"Eu, o Supremo\" e \"Filho de Homem\"."
  },
  "grupo-d-paraguai-07": {
    "nome": "Josefina Plá",
    "pais": "Paraguai",
    "grupo": "Grupo D",
    "numero": 7,
    "posicao": "Meia",
    "raridade": "Épico",
    "periodo": "1903-1999",
    "resumo": "Poeta, dramaturga, crítica de arte e jornalista de origem espanhola que se radicou e fez história no Paraguai.",
    "legado": "Considerada uma das figuras culturais mais influentes do século XX no país, foi pioneira na renovação das artes visuais e da literatura paraguaia."
  },
  "grupo-d-paraguai-08": {
    "nome": "Serafina Dávalos",
    "pais": "Paraguai",
    "grupo": "Grupo D",
    "numero": 8,
    "posicao": "Meia",
    "raridade": "Raro",
    "periodo": "1883-1957",
    "resumo": "Primeira mulher a se formar advogada no Paraguai e uma corajosa pioneira do pensamento feminista no país.",
    "legado": "Defendeu implacavelmente os direitos das mulheres, a educação feminina e a igualdade jurídica numa época altamente conservadora."
  },
  "grupo-d-paraguai-09": {
    "nome": "Agustín Barrios",
    "pais": "Paraguai",
    "grupo": "Grupo D",
    "numero": 9,
    "posicao": "Ponta",
    "raridade": "Épico",
    "periodo": "1885-1944",
    "resumo": "Também conhecido como Nitsuga Mangoré, foi um exímio violonista e um dos maiores compositores de música clássica da América Latina.",
    "legado": "Elevou o violão clássico a novos patamares, criando um repertório genial que mesclava o folclore sul-americano com técnicas complexas de estilo barroco."
  },
  "grupo-d-paraguai-10": {
    "nome": "Silvio Pettirossi",
    "pais": "Paraguai",
    "grupo": "Grupo D",
    "numero": 10,
    "posicao": "Camisa 10",
    "raridade": "Raro",
    "periodo": "1887-1916",
    "resumo": "Pioneiro da aviação nacional e o primeiro aviador paraguaio, famoso internacionalmente por suas manobras acrobáticas.",
    "legado": "Fundou o aeroclube do Paraguai; hoje, o principal aeroporto internacional do país ostenta o seu nome em homenagem."
  },
  "grupo-d-paraguai-11": {
    "nome": "José Asunción Flores",
    "pais": "Paraguai",
    "grupo": "Grupo D",
    "numero": 11,
    "posicao": "Centroavante",
    "raridade": "Comum",
    "periodo": "1904-1972",
    "resumo": "Músico e compositor brilhante, conhecido mundialmente por ser o criador do gênero musical \"Guarania\".",
    "legado": "A Guarania tornou-se a mais profunda expressão musical da alma paraguaia, combinando ritmos melancólicos e poesia autêntica."
  },
  "grupo-d-paraguai-12": {
    "nome": "Carmen Casco de Lara Castro",
    "pais": "Paraguai",
    "grupo": "Grupo D",
    "numero": 12,
    "posicao": "Técnica",
    "raridade": "Raro",
    "periodo": "1918-1993",
    "resumo": "Professora, líder política e ativista incansável pelos direitos humanos durante os duros anos de ditadura no país.",
    "legado": "Fundadora da Comissão de Defesa dos Direitos Humanos no Paraguai, dedicou a sua vida a proteger os perseguidos políticos e promover a liberdade."
  },
  "grupo-d-turquia-01": {
    "nome": "Mustafa Kemal Atatürk",
    "pais": "Turquia",
    "grupo": "Grupo D",
    "numero": 1,
    "posicao": "Goleiro",
    "raridade": "Lendário",
    "periodo": "1881-1938",
    "resumo": "Fundador e primeiro presidente da República da Turquia, liderou o Movimento Nacional Turco na Guerra de Independência.",
    "legado": "Modernizou e secularizou o país através de profundas reformas políticas, sociais e culturais, moldando a Turquia contemporânea."
  },
  "grupo-d-turquia-02": {
    "nome": "Mehmed II, o Conquistador",
    "pais": "Turquia",
    "grupo": "Grupo D",
    "numero": 2,
    "posicao": "Lateral",
    "raridade": "Épico",
    "periodo": "1432-1481",
    "resumo": "Sultão otomano que, aos 21 anos, comandou a histórica conquista de Constantinopla em 1453.",
    "legado": "Pôs fim ao Império Bizantino e transformou o Estado otomano num verdadeiro império, consolidando a ponte entre a Europa e a Ásia."
  },
  "grupo-d-turquia-03": {
    "nome": "Suleiman, o Magnífico",
    "pais": "Turquia",
    "grupo": "Grupo D",
    "numero": 3,
    "posicao": "Zagueiro",
    "raridade": "Lendário",
    "periodo": "1494-1566",
    "resumo": "O sultão que governou o Império Otomano durante mais tempo, conduzindo-o ao seu apogeu militar, político e económico.",
    "legado": "Conhecido localmente como \"O Legislador\" pela sua reestruturação completa do sistema jurídico otomano, foi também um grande patrono das artes e da arquitetura."
  },
  "grupo-d-turquia-04": {
    "nome": "Mimar Sinan",
    "pais": "Turquia",
    "grupo": "Grupo D",
    "numero": 4,
    "posicao": "Zagueiro",
    "raridade": "Raro",
    "periodo": "1490-1588",
    "resumo": "O arquiteto-chefe e engenheiro civil supremo de três sultões otomanos, responsável por obras monumentais.",
    "legado": "Projetou mais de 300 estruturas clássicas, incluindo a formidável Mesquita de Süleymaniye, definindo o estilo da arquitetura otomana."
  },
  "grupo-d-turquia-05": {
    "nome": "Piri Reis",
    "pais": "Turquia",
    "grupo": "Grupo D",
    "numero": 5,
    "posicao": "Lateral",
    "raridade": "Épico",
    "periodo": "1465-1553",
    "resumo": "Almirante, navegador, geógrafo e cartógrafo brilhante do Império Otomano.",
    "legado": "O seu famoso mapa-múndi de 1513 é um dos mapas mais antigos ainda existentes que representam o Novo Mundo (as Américas) com surpreendente precisão para a época."
  },
  "grupo-d-turquia-06": {
    "nome": "Yunus Emre",
    "pais": "Turquia",
    "grupo": "Grupo D",
    "numero": 6,
    "posicao": "Volante",
    "raridade": "Comum",
    "periodo": "1238-1320",
    "resumo": "Poeta folclórico e místico sufi que influenciou profundamente a cultura e a literatura da Anatólia.",
    "legado": "Foi um dos pioneiros a escrever os seus poemas no turco falado pelo povo (turco antigo), democratizando a poesia e o pensamento místico."
  },
  "grupo-d-turquia-07": {
    "nome": "Rumi",
    "pais": "Turquia",
    "grupo": "Grupo D",
    "numero": 7,
    "posicao": "Meia",
    "raridade": "Épico",
    "periodo": "1207-1273",
    "resumo": "Poeta persa, erudito islâmico, teólogo e místico sufi que viveu grande parte da sua vida em Konya, na Anatólia.",
    "legado": "A sua obra magna, \"Masnavi\", é considerada um dos mais elevados poemas da literatura mundial, e a sua filosofia transcendeu fronteiras nacionais e religiosas."
  },
  "grupo-d-turquia-08": {
    "nome": "Halide Edib Adıvar",
    "pais": "Turquia",
    "grupo": "Grupo D",
    "numero": 8,
    "posicao": "Meia",
    "raridade": "Raro",
    "periodo": "1884-1964",
    "resumo": "Romancista, líder nacionalista e pioneira nos direitos das mulheres, atuou ativamente na Guerra da Independência.",
    "legado": "A sua literatura capturou a transformação da sociedade turca e foi fundamental para elevar a posição das mulheres na nova república."
  },
  "grupo-d-turquia-09": {
    "nome": "Sabiha Gökçen",
    "pais": "Turquia",
    "grupo": "Grupo D",
    "numero": 9,
    "posicao": "Ponta",
    "raridade": "Raro",
    "periodo": "1913-2001",
    "resumo": "Filha adotiva de Atatürk, entrou para a história como a primeira mulher piloto de combate do mundo aos 23 anos.",
    "legado": "É o símbolo máximo da emancipação feminina e da modernização impulsionada pela República Turca, inspirando gerações de mulheres na aviação."
  },
  "grupo-d-turquia-10": {
    "nome": "Evliya Çelebi",
    "pais": "Turquia",
    "grupo": "Grupo D",
    "numero": 10,
    "posicao": "Camisa 10",
    "raridade": "Comum",
    "periodo": "1611-1682",
    "resumo": "Famoso explorador otomano que viajou através dos territórios do império e das terras vizinhas durante um período de quarenta anos.",
    "legado": "A sua obra de dez volumes, o \"Seyahatname\" (Livro de Viagens), é uma fonte histórica e linguística de valor incalculável sobre a vida e a cultura do século XVII."
  },
  "grupo-d-turquia-11": {
    "nome": "Alp Arslan",
    "pais": "Turquia",
    "grupo": "Grupo D",
    "numero": 11,
    "posicao": "Centroavante",
    "raridade": "Épico",
    "periodo": "1029-1072",
    "resumo": "Segundo sultão do Império Seljúcida e um brilhante estratega militar, líder das tribos turcomenas.",
    "legado": "A sua vitória decisiva na Batalha de Manziquerta (1071) abriu as portas da Anatólia para a colonização turca, mudando para sempre o rumo da história na região."
  },
  "grupo-d-turquia-12": {
    "nome": "Kösem Sultan",
    "pais": "Turquia",
    "grupo": "Grupo D",
    "numero": 12,
    "posicao": "Técnica",
    "raridade": "Raro",
    "periodo": "1589-1651",
    "resumo": "Uma das mulheres mais poderosas da história otomana, atuou como regente do império num período de grande turbulência.",
    "legado": "Exerceu uma influência política sem precedentes através dos seus filhos e netos, marcando a era conhecida como o \"Sultanato das Mulheres\"."
  }
});
