window.FICHAS_TECNICAS = window.FICHAS_TECNICAS || {};
// Fichas técnicas - GRUPO-G
Object.assign(window.FICHAS_TECNICAS, {
  "grupo-g-belgica-01": {
    "nome": "René Magritte",
    "pais": "Bélgica",
    "grupo": "Grupo G",
    "numero": 1,
    "posicao": "Goleiro",
    "raridade": "Lendário",
    "periodo": "1898-1967",
    "resumo": "Um dos mais proeminentes pintores surrealistas do mundo.",
    "legado": "Desafiou a percepção da realidade com obras instigantes, sendo imortalizado por quadros como \"O Filho do Homem\" e \"A Traição das Imagens\"."
  },
  "grupo-g-belgica-02": {
    "nome": "Hergé (Georges Remi)",
    "pais": "Bélgica",
    "grupo": "Grupo G",
    "numero": 2,
    "posicao": "Lateral",
    "raridade": "Comum",
    "periodo": "1907-1983",
    "resumo": "Cartunista e ilustrador pioneiro.",
    "legado": "Criador de \"As Aventuras de Tintim\", revolucionou as histórias em quadrinhos europeias com o seu estilo de \"linha clara\"."
  },
  "grupo-g-belgica-03": {
    "nome": "Peter Paul Rubens",
    "pais": "Bélgica",
    "grupo": "Grupo G",
    "numero": 3,
    "posicao": "Zagueiro",
    "raridade": "Raro",
    "periodo": "1577-1640",
    "resumo": "Pintor flamengo e diplomata proeminente do século XVII.",
    "legado": "O maior expoente do estilo barroco flamengo, famoso pelas suas obras dinâmicas, coloridas e sensuais que definiram uma era artística."
  },
  "grupo-g-belgica-04": {
    "nome": "Gerardus Mercator",
    "pais": "Bélgica",
    "grupo": "Grupo G",
    "numero": 4,
    "posicao": "Zagueiro",
    "raridade": "Comum",
    "periodo": "1512-1594",
    "resumo": "Geógrafo, cosmógrafo e cartógrafo renascentista.",
    "legado": "Criou a Projeção de Mercator em 1569, uma revolução na navegação marítima que ainda hoje é a base de muitos mapas globais."
  },
  "grupo-g-belgica-05": {
    "nome": "Adolphe Sax",
    "pais": "Bélgica",
    "grupo": "Grupo G",
    "numero": 5,
    "posicao": "Lateral",
    "raridade": "Lendário",
    "periodo": "1814-1894",
    "resumo": "Inventor e fabricante de instrumentos musicais.",
    "legado": "Inventou o saxofone em 1846, transformando para sempre a música mundial, especialmente o jazz e as bandas militares."
  },
  "grupo-g-belgica-06": {
    "nome": "Georges Lemaître",
    "pais": "Bélgica",
    "grupo": "Grupo G",
    "numero": 6,
    "posicao": "Volante",
    "raridade": "Comum",
    "periodo": "1894-1966",
    "resumo": "Padre católico, astrônomo e professor de física.",
    "legado": "Foi o primeiro a propor a teoria da expansão do universo, que hoje conhecemos como a Teoria do Big Bang."
  },
  "grupo-g-belgica-07": {
    "nome": "Victor Horta",
    "pais": "Bélgica",
    "grupo": "Grupo G",
    "numero": 7,
    "posicao": "Meia",
    "raridade": "Épico",
    "periodo": "1861-1947",
    "resumo": "Arquiteto e designer revolucionário.",
    "legado": "Considerado um dos fundadores do movimento Art Nouveau, quebrou as tradições arquitetônicas com o uso inovador de ferro, vidro e formas orgânicas."
  },
  "grupo-g-belgica-08": {
    "nome": "Andreas Vesalius",
    "pais": "Bélgica",
    "grupo": "Grupo G",
    "numero": 8,
    "posicao": "Meia",
    "raridade": "Comum",
    "periodo": "1514-1564",
    "resumo": "Médico e anatomista do Renascimento.",
    "legado": "Autor de \"De humani corporis fabrica\", é considerado o pai da anatomia humana moderna por suas dissecações e descrições precisas."
  },
  "grupo-g-belgica-09": {
    "nome": "Jacques Brel",
    "pais": "Bélgica",
    "grupo": "Grupo G",
    "numero": 9,
    "posicao": "Ponta",
    "raridade": "Raro",
    "periodo": "1929-1978",
    "resumo": "Cantor, compositor, ator e diretor icônico.",
    "legado": "Mestre da \"chanson\" francesa moderna, suas performances teatrais e letras poéticas influenciaram músicos em todo o mundo."
  },
  "grupo-g-belgica-10": {
    "nome": "Rei Leopoldo I",
    "pais": "Bélgica",
    "grupo": "Grupo G",
    "numero": 10,
    "posicao": "Camisa 10",
    "raridade": "Comum",
    "periodo": "1790-1865",
    "resumo": "O primeiro Rei dos Belgas após a independência do país em 1830.",
    "legado": "Estabeleceu e consolidou o novo reino, promoveu a industrialização (incluindo a primeira ferrovia da Europa continental) e manteve a Bélgica neutra."
  },
  "grupo-g-belgica-11": {
    "nome": "Marguerite Yourcenar",
    "pais": "Bélgica",
    "grupo": "Grupo G",
    "numero": 11,
    "posicao": "Centroavante",
    "raridade": "Comum",
    "periodo": "1903-1987",
    "resumo": "Romancista e ensaísta nascida em Bruxelas.",
    "legado": "Autora de \"Memórias de Adriano\", foi a primeira mulher a ser eleita para a prestigiosa Academia Francesa."
  },
  "grupo-g-belgica-12": {
    "nome": "Marie Popelin",
    "pais": "Bélgica",
    "grupo": "Grupo G",
    "numero": 12,
    "posicao": "Técnica",
    "raridade": "Lendário",
    "periodo": "1846-1913",
    "resumo": "Pioneira feminista e a primeira mulher a obter um doutorado em Direito na Bélgica.",
    "legado": "Teve sua licença para advogar negada por ser mulher, o que desencadeou o movimento moderno pelos direitos das mulheres no país."
  },
  "grupo-g-egito-01": {
    "nome": "Khufu (Quéops)",
    "pais": "Egito",
    "grupo": "Grupo G",
    "numero": 1,
    "posicao": "Goleiro",
    "raridade": "Lendário",
    "periodo": "~2589–2566 a.C.",
    "resumo": "Faraó da Quarta Dinastia do Império Antigo.",
    "legado": "Encomendou a Grande Pirâmide de Gizé, a única das Sete Maravilhas do Mundo Antigo que ainda permanece amplamente intacta."
  },
  "grupo-g-egito-02": {
    "nome": "Akhenaten",
    "pais": "Egito",
    "grupo": "Grupo G",
    "numero": 2,
    "posicao": "Lateral",
    "raridade": "Comum",
    "periodo": "~1353–1336 a.C.",
    "resumo": "Faraó da Décima Oitava Dinastia.",
    "legado": "Conhecido como o \"Faraó Herege\" por abandonar o politeísmo egípcio tradicional em favor do culto exclusivo a Aten, um dos primeiros monoteísmos da história."
  },
  "grupo-g-egito-03": {
    "nome": "Ramsés II (O Grande)",
    "pais": "Egito",
    "grupo": "Grupo G",
    "numero": 3,
    "posicao": "Zagueiro",
    "raridade": "Raro",
    "periodo": "~1303–1213 a.C.",
    "resumo": "O terceiro faraó da Décima Nona Dinastia.",
    "legado": "Um dos mais poderosos e celebrados faraós, liderou expansões militares, assinou o primeiro tratado de paz registrado e construiu monumentos colossais como Abu Simbel."
  },
  "grupo-g-egito-04": {
    "nome": "Hatshepsut",
    "pais": "Egito",
    "grupo": "Grupo G",
    "numero": 4,
    "posicao": "Zagueira",
    "raridade": "Comum",
    "periodo": "~1507–1458 a.C.",
    "resumo": "Uma das poucas mulheres a governar como faraó com plenos poderes.",
    "legado": "Seu reinado pacífico foi marcado por imensa prosperidade, redes comerciais expandidas e maravilhas arquitetônicas, como seu templo em Deir el-Bahari."
  },
  "grupo-g-egito-05": {
    "nome": "Cleópatra VII",
    "pais": "Egito",
    "grupo": "Grupo G",
    "numero": 5,
    "posicao": "Lateral",
    "raridade": "Lendário",
    "periodo": "69–30 a.C.",
    "resumo": "A última governante ativa do Reino Ptolomaico do Egito.",
    "legado": "Brilhante diplomata, linguista e estrategista política, lutou para proteger a independência do Egito frente ao expansionismo de Roma."
  },
  "grupo-g-egito-06": {
    "nome": "Umm Kulthum",
    "pais": "Egito",
    "grupo": "Grupo G",
    "numero": 6,
    "posicao": "Volante",
    "raridade": "Comum",
    "periodo": "1898-1975",
    "resumo": "Cantora, compositora e atriz.",
    "legado": "Conhecida como a \"Estrela do Oriente\", é considerada a maior cantora árabe da história, unindo o mundo árabe através de sua voz incomparável."
  },
  "grupo-g-egito-07": {
    "nome": "Naguib Mahfouz",
    "pais": "Egito",
    "grupo": "Grupo G",
    "numero": 7,
    "posicao": "Meia",
    "raridade": "Épico",
    "periodo": "1911-2006",
    "resumo": "Romancista prolífico e intelectual.",
    "legado": "Ganhou o Prêmio Nobel de Literatura em 1988 (o primeiro escritor árabe a consegui-lo), modernizando a literatura árabe com o seu retrato realista do Egito."
  },
  "grupo-g-egito-08": {
    "nome": "Ahmed Zewail",
    "pais": "Egito",
    "grupo": "Grupo G",
    "numero": 8,
    "posicao": "Meia",
    "raridade": "Comum",
    "periodo": "1946-2016",
    "resumo": "Cientista e acadêmico especializado em femtoquímica.",
    "legado": "Vencedor do Prêmio Nobel de Química em 1999 pelo estudo de reações químicas em escalas de tempo ultracurtas (femtosegundos)."
  },
  "grupo-g-egito-09": {
    "nome": "Gamal Abdel Nasser",
    "pais": "Egito",
    "grupo": "Grupo G",
    "numero": 9,
    "posicao": "Ponta",
    "raridade": "Raro",
    "periodo": "1918-1970",
    "resumo": "Segundo presidente do Egito e líder da Revolução de 1952.",
    "legado": "Defensor do pan-arabismo e da justiça social, nacionalizou o Canal de Suez e tornou-se um símbolo imenso de dignidade e independência anti-imperialista no mundo árabe."
  },
  "grupo-g-egito-10": {
    "nome": "Salah ad-Din (Saladino)",
    "pais": "Egito",
    "grupo": "Grupo G",
    "numero": 10,
    "posicao": "Camisa 10",
    "raridade": "Comum",
    "periodo": "1137-1193",
    "resumo": "Fundador da dinastia Aiúbida, foi Sultão do Egito e da Síria.",
    "legado": "Famoso por sua nobreza militar e cavalheirismo, reconquistou Jerusalém dos Cruzados em 1187 e repeliu a Terceira Cruzada."
  },
  "grupo-g-egito-11": {
    "nome": "Tutankhamun",
    "pais": "Egito",
    "grupo": "Grupo G",
    "numero": 11,
    "posicao": "Centroavante",
    "raridade": "Comum",
    "periodo": "~1341–1323 a.C.",
    "resumo": "Jovem faraó que reverteu as reformas religiosas de seu pai (Akhenaten).",
    "legado": "Seu túmulo incrivelmente preservado, descoberto em 1922, tornou-se a descoberta arqueológica mais famosa do mundo, definindo a imagem moderna do Antigo Egito."
  },
  "grupo-g-egito-12": {
    "nome": "Nefertiti",
    "pais": "Egito",
    "grupo": "Grupo G",
    "numero": 12,
    "posicao": "Técnica",
    "raridade": "Lendário",
    "periodo": "~1370–1330 a.C.",
    "resumo": "Grande Esposa Real do faraó Akhenaten.",
    "legado": "Exerceu um poder e influência sem precedentes, co-reinando na revolução religiosa de Amarna; seu busto icônico é um dos maiores símbolos de beleza da antiguidade."
  },
  "grupo-g-ira-01": {
    "nome": "Ciro, o Grande",
    "pais": "Irã",
    "grupo": "Grupo G",
    "numero": 1,
    "posicao": "Goleiro",
    "raridade": "Lendário",
    "periodo": "~600–530 a.C.",
    "resumo": "Fundador do Império Aquemênida, o maior império que o mundo já havia visto até então.",
    "legado": "Respeitado por sua tolerância religiosa e política de direitos humanos pioneira (O Cilindro de Ciro), unificou o Oriente Médio sob um governo centralizado."
  },
  "grupo-g-ira-02": {
    "nome": "Ferdowsi",
    "pais": "Irã",
    "grupo": "Grupo G",
    "numero": 2,
    "posicao": "Lateral",
    "raridade": "Comum",
    "periodo": "940-1020",
    "resumo": "Um dos maiores poetas épicos da literatura persa.",
    "legado": "Escreveu o monumental \"Shahnameh\" (O Livro dos Reis), que salvou e revitalizou a língua, a história e a identidade persa após a conquista árabe."
  },
  "grupo-g-ira-03": {
    "nome": "Avicena (Ibn Sina)",
    "pais": "Irã",
    "grupo": "Grupo G",
    "numero": 3,
    "posicao": "Zagueiro",
    "raridade": "Raro",
    "periodo": "980-1037",
    "resumo": "Polímata, médico, astrônomo e filósofo.",
    "legado": "O seu \"Cânone da Medicina\" foi o principal texto médico na Europa e no mundo islâmico durante séculos; um dos pensadores mais importantes da Era de Ouro Islâmica."
  },
  "grupo-g-ira-04": {
    "nome": "Omar Khayyam",
    "pais": "Irã",
    "grupo": "Grupo G",
    "numero": 4,
    "posicao": "Zagueiro",
    "raridade": "Comum",
    "periodo": "1048-1131",
    "resumo": "Matemático, astrônomo, filósofo e poeta.",
    "legado": "Fez avanços cruciais na álgebra e no calendário, mas é globalmente imortalizado pela sua poesia atemporal e filosófica no \"Rubaiyat\"."
  },
  "grupo-g-ira-05": {
    "nome": "Dario, o Grande",
    "pais": "Irã",
    "grupo": "Grupo G",
    "numero": 5,
    "posicao": "Lateral",
    "raridade": "Lendário",
    "periodo": "550-486 a.C.",
    "resumo": "Terceiro Rei dos Reis do Império Aquemênida.",
    "legado": "Administrador genial, dividiu o império em províncias (satrapias), criou estradas monumentais, padronizou a moeda e encomendou a capital cerimonial de Persépolis."
  },
  "grupo-g-ira-06": {
    "nome": "Al-Razi",
    "pais": "Irã",
    "grupo": "Grupo G",
    "numero": 6,
    "posicao": "Volante",
    "raridade": "Comum",
    "periodo": "865-925",
    "resumo": "Médico, alquimista, filósofo e pioneiro da pediatria.",
    "legado": "Fez a primeira distinção médica clara entre a varíola e o sarampo e descobriu inúmeros compostos, moldando a química e a medicina medieval."
  },
  "grupo-g-ira-07": {
    "nome": "Hafez",
    "pais": "Irã",
    "grupo": "Grupo G",
    "numero": 7,
    "posicao": "Meia",
    "raridade": "Épico",
    "periodo": "1315-1390",
    "resumo": "O poeta lírico mais reverenciado da literatura persa.",
    "legado": "Seus poemas exploram o amor místico, o vinho e a crítica à hipocrisia, sendo memorizados, cantados e usados como orientação espiritual no Irã até os dias de hoje."
  },
  "grupo-g-ira-08": {
    "nome": "Amir Kabir",
    "pais": "Irã",
    "grupo": "Grupo G",
    "numero": 8,
    "posicao": "Meia",
    "raridade": "Comum",
    "periodo": "1807-1852",
    "resumo": "Primeiro-ministro sob o Xá Naser al-Din na dinastia Qajar.",
    "legado": "Empreendeu profundas reformas de modernização no Irã, fundando o Dar ul-Funun (primeira universidade moderna) e centralizando a administração do Estado."
  },
  "grupo-g-ira-09": {
    "nome": "Shah Abbas I (O Grande)",
    "pais": "Irã",
    "grupo": "Grupo G",
    "numero": 9,
    "posicao": "Ponta",
    "raridade": "Raro",
    "periodo": "1571-1629",
    "resumo": "O monarca mais forte da dinastia Safávida.",
    "legado": "Revitalizou o império, promoveu o comércio internacional, apoiou as artes de forma formidável e transformou Isfahan numa das cidades mais belas do mundo."
  },
  "grupo-g-ira-10": {
    "nome": "Nader Shah",
    "pais": "Irã",
    "grupo": "Grupo G",
    "numero": 10,
    "posicao": "Camisa 10",
    "raridade": "Comum",
    "periodo": "1688-1747",
    "resumo": "Fundador da dinastia Afexárida e brilhante comandante militar.",
    "legado": "Conhecido como a \"Espada da Pérsia\" ou \"Napoleão do Oriente\", repeliu invasores otomanos e russos e restaurou as fronteiras e o prestígio iraniano no século XVIII."
  },
  "grupo-g-ira-11": {
    "nome": "Forough Farrokhzad",
    "pais": "Irã",
    "grupo": "Grupo G",
    "numero": 11,
    "posicao": "Centroavante",
    "raridade": "Comum",
    "periodo": "1934-1967",
    "resumo": "Poetisa vanguardista e diretora de cinema.",
    "legado": "Uma das vozes femininas mais importantes da literatura persa do século XX, quebrou tabus culturais ao escrever com profunda vulnerabilidade, desafio e paixão."
  },
  "grupo-g-ira-12": {
    "nome": "Maryam Mirzakhani",
    "pais": "Irã",
    "grupo": "Grupo G",
    "numero": 12,
    "posicao": "Técnica",
    "raridade": "Lendário",
    "periodo": "1977-2017",
    "resumo": "Brilhante matemática teórica e professora.",
    "legado": "A primeira mulher e a primeira pessoa iraniana a ser homenageada com a Medalha Fields (o \"Nobel da Matemática\") por seu trabalho inovador na geometria de superfícies complexas."
  },
  "grupo-g-nova-zelandia-01": {
    "nome": "Kupe",
    "pais": "Nova Zelândia",
    "grupo": "Grupo G",
    "numero": 1,
    "posicao": "Goleiro",
    "raridade": "Lendário",
    "periodo": "~Século X a XIV (Datação Tradicional Polinésia)",
    "resumo": "Lendário explorador polinésio.",
    "legado": "Na tradição oral Māori, foi o primeiro ser humano a descobrir a Nova Zelândia (Aotearoa), navegando as vastas águas do Pacífico através das estrelas."
  },
  "grupo-g-nova-zelandia-02": {
    "nome": "Kate Sheppard",
    "pais": "Nova Zelândia",
    "grupo": "Grupo G",
    "numero": 2,
    "posicao": "Lateral",
    "raridade": "Comum",
    "periodo": "1847-1934",
    "resumo": "Líder do movimento sufragista da Nova Zelândia.",
    "legado": "Liderou a campanha histórica que, em 1893, fez da Nova Zelândia a primeira nação governada democraticamente no mundo a garantir o direito de voto às mulheres."
  },
  "grupo-g-nova-zelandia-03": {
    "nome": "Ernest Rutherford",
    "pais": "Nova Zelândia",
    "grupo": "Grupo G",
    "numero": 3,
    "posicao": "Zagueiro",
    "raridade": "Raro",
    "periodo": "1871-1937",
    "resumo": "Físico nascido em Nelson, famoso por seu trabalho revolucionário em radioatividade e estrutura atômica.",
    "legado": "O \"pai da física nuclear\", vencedor do Nobel de Química; descobriu o núcleo atômico e foi a primeira pessoa a dividir um átomo intencionalmente."
  },
  "grupo-g-nova-zelandia-04": {
    "nome": "Jean Batten",
    "pais": "Nova Zelândia",
    "grupo": "Grupo G",
    "numero": 4,
    "posicao": "Zagueira",
    "raridade": "Comum",
    "periodo": "1909-1982",
    "resumo": "Aviadora célebre e desbravadora dos ares.",
    "legado": "Realizou voos solo recordistas globais na década de 1930, incluindo o primeiro voo solo da Inglaterra para a Nova Zelândia em 1936."
  },
  "grupo-g-nova-zelandia-05": {
    "nome": "Sir Edmund Hillary",
    "pais": "Nova Zelândia",
    "grupo": "Grupo G",
    "numero": 5,
    "posicao": "Lateral",
    "raridade": "Lendário",
    "periodo": "1919-2008",
    "resumo": "Alpinista, explorador e filantropo.",
    "legado": "Juntamente com Tenzing Norgay, tornou-se o primeiro montanhista confirmado a alcançar o cume do Monte Everest (1953), dedicando o resto de sua vida a ajudar o povo Sherpa do Nepal."
  },
  "grupo-g-nova-zelandia-06": {
    "nome": "Sir Apirana Ngata",
    "pais": "Nova Zelândia",
    "grupo": "Grupo G",
    "numero": 6,
    "posicao": "Volante",
    "raridade": "Comum",
    "periodo": "1874-1950",
    "resumo": "Advogado, político e figura proeminente da liderança Māori.",
    "legado": "Trabalhou incansavelmente pelo renascimento e proteção da cultura, da língua e do desenvolvimento econômico dos povos indígenas na era moderna."
  },
  "grupo-g-nova-zelandia-07": {
    "nome": "Dame Whina Cooper",
    "pais": "Nova Zelândia",
    "grupo": "Grupo G",
    "numero": 7,
    "posicao": "Meia",
    "raridade": "Épico",
    "periodo": "1895-1994",
    "resumo": "Respeitada líder comunitária e ativista (conhecida como \"Te Whaea o te Motu\" - a Mãe da Nação).",
    "legado": "Aos 79 anos, liderou a lendária marcha de protesto (Hīkoi) de 1975 por toda a Ilha Norte para exigir direitos sobre a terra e justiça para os Māori."
  },
  "grupo-g-nova-zelandia-08": {
    "nome": "Katherine Mansfield",
    "pais": "Nova Zelândia",
    "grupo": "Grupo G",
    "numero": 8,
    "posicao": "Meia",
    "raridade": "Comum",
    "periodo": "1888-1923",
    "resumo": "Renomada escritora de ficção modernista e ensaísta.",
    "legado": "Mestre do conto curto, revolucionou a narrativa com sua focagem na psicologia interior e percepção aguçada da condição humana, ganhando aclamação global."
  },
  "grupo-g-nova-zelandia-09": {
    "nome": "Charles Upham",
    "pais": "Nova Zelândia",
    "grupo": "Grupo G",
    "numero": 9,
    "posicao": "Ponta",
    "raridade": "Raro",
    "periodo": "1908-1994",
    "resumo": "Soldado heroico que serviu durante a Segunda Guerra Mundial.",
    "legado": "Um dos soldados mais condecorados da história militar da Commonwealth, sendo a única força de combate a receber a Cruz Vitória duas vezes (VC & Bar) durante a Segunda Guerra."
  },
  "grupo-g-nova-zelandia-10": {
    "nome": "Richard Seddon",
    "pais": "Nova Zelândia",
    "grupo": "Grupo G",
    "numero": 10,
    "posicao": "Camisa 10",
    "raridade": "Comum",
    "periodo": "1845-1906",
    "resumo": "O Primeiro-Ministro com mais tempo de mandato na história do país.",
    "legado": "Dominou a política da era dourada reformista, introduzindo pensões por idade avançada e assinando a lei histórica que garantiu o voto feminino."
  },
  "grupo-g-nova-zelandia-11": {
    "nome": "Hone Heke",
    "pais": "Nova Zelândia",
    "grupo": "Grupo G",
    "numero": 11,
    "posicao": "Centroavante",
    "raridade": "Comum",
    "periodo": "~1807-1850",
    "resumo": "Líder e guerreiro formidável da tribo Ngāpuhi.",
    "legado": "Figura altamente influente na assinatura inicial do Tratado de Waitangi; posteriormente defendeu ferozmente a soberania de seu povo derrubando o mastro da bandeira britânica."
  },
  "grupo-g-nova-zelandia-12": {
    "nome": "Te Rauparaha",
    "pais": "Nova Zelândia",
    "grupo": "Grupo G",
    "numero": 12,
    "posicao": "Técnico",
    "raridade": "Lendário",
    "periodo": "~1768-1849",
    "resumo": "Notório chefe militar e estrategista da tribo Ngāti Toa.",
    "legado": "Compositor do mundialmente famoso Haka \"Ka Mate\" (realizado pela seleção All Blacks), foi um líder engenhoso durante o turbulento período de contato europeu."
  }
});
